- mod-orders-storage/examples/details_get.sample
- mod-orders-storage/examples/details_post.sample
- mod-orders-storage/examples/eresource_collection.sample
- mod-orders-storage/examples/eresource_get.sample
- mod-orders-storage/examples/eresource_post.sample
- mod-orders-storage/examples/license_collection.sample
- mod-orders-storage/examples/license_get.sample
- mod-orders-storage/examples/license_post.sample
- mod-orders-storage/examples/location_collection.sample
- mod-orders-storage/examples/location_get.sample
- mod-orders-storage/examples/location_post.sample
- mod-orders-storage/examples/physical_collection.sample
- mod-orders-storage/examples/physical_get.sample
- mod-orders-storage/examples/physical_post.sample
Fixed various errors with JSON examples in mod-orders-storage
Also verified the rest of acq-models
> MODORDSTOR-7 fix broken json

- composite_po_line.json
- composite_purchase_order.json
- examples/composite_purchase_order.sample
- mod-orders-storage/examples/fund_distribution_collection.sample
- mod-orders-storage/examples/fund_distribution_get.sample
- mod-orders-storage/examples/fund_distribution_post.sample
- mod-orders-storage/examples/po_line_collection.sample
- mod-orders-storage/examples/po_line_get.sample
- mod-orders-storage/examples/po_line_post.sample
- mod-orders-storage/examples/purchase_order_collection.sample
- mod-orders-storage/examples/purchase_order_get.sample
- mod-orders-storage/examples/purchase_order_post.sample
- mod-orders-storage/schemas/fund_distribution.json
- mod-orders-storage/schemas/fund_distribution_collection.json
- mod-orders-storage/schemas/po_line.json
- mod-orders-storage/schemas/purchase_order.json
See [MODORDERS-51](https://issues.folio.org/browse/MODORDERS-51)
> MODORDERS-51 add fund_dist, vendor_detail, manual_po

- NEWS.md
- composite_purchase_order.json
- examples/composite_purchase_order.sample
- examples/composite_purchase_orders.sample
See [MODORDERS-53 ](https://issues.folio.org/browse/MODORDERS-53) for additional details.
> MODORDERS-53 - CompositePurchaseOrder needs a top-level ID field

- examples/composite_po_line.sample
Adding sample for composite_po_line which is going to be used in mod-orders/ramls/order.raml
> MODORDERS-75 Define new order line endpoints

- checkins.json
- examples/checkins.sample
- examples/receivings.sample
- receivings.json
Initial (draft) version of the 'receivings' and 'check-ins' schemas
> MODORDERS-71 Create draft receiving schemas

- examples/composite_po_line.sample
- examples/composite_purchase_order.sample
- mod-orders-storage/examples/physical_collection.sample
- mod-orders-storage/examples/physical_get.sample
- mod-orders-storage/examples/physical_post.sample
- mod-orders-storage/examples/po_line_collection.sample
- mod-orders-storage/examples/po_line_get.sample
- mod-orders-storage/examples/po_line_post.sample
- mod-orders-storage/schemas/physical.json
- mod-orders-storage/schemas/po_line.json
As per [MODORDERS-70](https://issues.folio.org/browse/MODORDERS-70) the changes need to be done for PO Line and Physical Material schemas to accommodate business requirements.
- 'po_line' and 'physical' schemas were updated to accommodate required changes
- all affected samples were updated
> MODORDERS-70 Orders schema updates

- mod-orders-storage/examples/piece_collection.sample
- mod-orders-storage/examples/piece_get.sample
- mod-orders-storage/examples/piece_post.sample
- mod-orders-storage/schemas/piece.json
- mod-orders-storage/schemas/piece_collection.json
Added the details for piece schema.
> MODORDSTOR-30 : Piece schema

- mod-orders-storage/schemas/close_reason.json
fixed close_reason.json schema bug
> "white space" bug fix for close reason object

- Jenkinsfile
Assess the JSON schema descriptions at this shared source repository.
> FOLIO-1447 Add Jenkinsfile do "lint raml schema"

- composite_po_line.json
- composite_purchase_order.json
- examples/composite_po_line.sample
- examples/composite_purchase_order.sample
- examples/composite_purchase_orders.sample
- mod-orders-storage/examples/po_line_collection.sample
- mod-orders-storage/examples/po_line_get.sample
- mod-orders-storage/examples/po_line_post.sample
- mod-orders-storage/examples/purchase_order_collection.sample
- mod-orders-storage/examples/purchase_order_get.sample
- mod-orders-storage/examples/purchase_order_post.sample
- mod-orders-storage/schemas/po_line.json
- mod-orders-storage/schemas/purchase_order.json
- replaced created and created_by fields with metadata in po_line.json, purchase_order.json, composite_po_line.json, composite_purchase_order.json
- samples updated
> MODORDSTOR-35 GET purchase_order and po_line don't have created_by in response

- mod-vendors/examples/agreement_collection.sample
- mod-vendors/examples/agreement_get.sample
- mod-vendors/examples/agreement_post.sample
- mod-vendors/examples/contact_person_collection.sample
- mod-vendors/examples/contact_person_get.sample
- mod-vendors/examples/contact_person_post.sample
- mod-vendors/examples/vendor_collection.sample
- mod-vendors/examples/vendor_contact_person_collection.sample
- mod-vendors/examples/vendor_contact_person_get.sample
- mod-vendors/examples/vendor_contact_person_post.sample
- mod-vendors/examples/vendor_get.sample
- mod-vendors/examples/vendor_phone_collection.sample
- mod-vendors/examples/vendor_phone_get.sample
- mod-vendors/examples/vendor_phone_post.sample
- mod-vendors/examples/vendor_post.sample
- mod-vendors/examples/vendor_type_get.sample
- mod-vendors/schemas/vendor_type.json
Fixes in example data and models to resolve raml-cop issues in mod-vendors.
> Modvend 66

- NEWS.md
- mod-orders-storage/examples/receiving_history_collection.sample
- mod-orders-storage/examples/receiving_history_get.sample
- mod-orders-storage/schemas/receiving_history.json
- mod-orders-storage/schemas/receiving_history_collection.json
Define schema - https://issues.folio.org/browse/MODORDSTOR-31
> MODORDSTOR-31 receiving_history schema

- NEWS.md
- composite_purchase_order.json
- examples/composite_purchase_order.sample
- examples/composite_purchase_orders.sample
- mod-orders-storage/examples/purchase_order_collection.sample
- mod-orders-storage/examples/purchase_order_get.sample
- mod-orders-storage/examples/purchase_order_post.sample
- mod-orders-storage/schemas/po_number.json
- mod-orders-storage/schemas/purchase_order.json
Remove `poNumberPrefix` and `poNumberSuffix`
> MODORDERS-108 Update purchase order schemas

- PULL_REQUEST_TEMPLATE.md
- mod-orders-storage/examples/piece_collection.sample
- mod-orders-storage/examples/piece_get.sample
- mod-orders-storage/examples/piece_post.sample
- mod-orders-storage/schemas/piece.json
- mod-orders-storage/schemas/piece_collection.json
https://issues.folio.org/browse/MODORDERS-138
- Change fields to camelCase as per [FOLIO Naming conventions](https://dev.folio.org/guidelines/naming-conventions/#permissions)
- Remove caption, supplement fields from required
> Update required fields and change to camelCase

- README.md
- examples/composite_po_line.sample
- examples/composite_purchase_order.sample
- mod-orders-storage/examples/physical_collection.sample
- mod-orders-storage/examples/physical_get.sample
- mod-orders-storage/examples/physical_post.sample
- mod-orders-storage/schemas/physical.json
There is another data element "expectedReceiptDate" to be provided and stored for PO line which is currently missing in the schema.
* Update physical.json schema with a new element
* Update all related sample data
> MODORDERS-135 Update Physical schema: Add expected_receipt_date

- mod-vendors/examples/contact_collection.sample
- mod-vendors/schemas/edi_ftp.json
- mod-vendors/schemas/url.json
Changes were made to the regex used to enforce url formatting in edi_ftp and url models.
The regex changes have been applied, and verified to work in the CI environment as part of https://github.com/folio-org/mod-vendors/pull/47
- [y] Examples exist for all schemas
- [y] Descriptions exist for all schema properties
- [y] All schemas pass raml-cop linting
- [n] Were there any schema changes?
- [n] There are no breaking changes in this PR.
- Do JIRAs exist to update the impacted …
> Modvend 85 Updates to regex

- mod-orders-storage/examples/piece_collection.sample
- mod-orders-storage/examples/piece_get.sample
- mod-orders-storage/examples/piece_post.sample
- mod-orders-storage/examples/receiving_history_collection.sample
- mod-orders-storage/examples/receiving_history_get.sample
- mod-orders-storage/schemas/piece.json
- mod-orders-storage/schemas/receiving_history.json
[MODORDERS-166](https://issues.folio.org/browse/MODORDERS-166) Add locationId to the piece schema
[MODORDERS-165](https://issues.folio.org/browse/MODORDERS-165) Add location to receiving_history
- piece and receiving_history schemas updated
- examples updated …
> MODORDERS-166/MODORDERS-165 Add locationId to piece and receiving_history schemas

- mod-finance/examples/ledger.sample
- mod-finance/examples/ledger_collection.sample
https://issues.folio.org/browse/MODFISTO-5
Updating RMB module version 19.0 to 23.11 revealed a bug with not valid sample data.
(There is only 30 days in June)
Setting valid date for ledger sample data
> MODFISTO-5 fixed period_end date

- mod-orgs/examples/organization_collection.sample
- mod-orgs/examples/organization_get.sample
- mod-orgs/examples/organization_post.sample
- mod-orgs/examples/organization_put.sample
- mod-orgs/schemas/organization.json
[MODORGS-20](https://issues.folio.org/browse/MODORGS-20) The organizations schema has references (UUID) to an interface records, as opposed to storing the interface data directly in the organization record.
Replacing reference to schema (interface.json) by string (UUID)
> MODORGS-20 interface references

- mod-orgs/examples/organization_collection.sample
The organization sample is having incorrect format for few sub objects
fix the fields according to the organization schema
> Fix Organization sample file

- mod-invoice-storage/schemas/invoice.json
Ann-Marie requested a small change to the phrasing of the vendorInvoiceNo field description. …
> MODINVOICE-14 - Minor change to the vendorInvoiceNo description

- mod-invoice-storage/schemas/invoice.json
[MODINVOICE-20](https://issues.folio.org/browse/MODINVOICE-20) FOLIO invoice number always system generated, so it can not be required
- making folioInvoiceNo not required …
> MODINVOICE-20 Implement POST /invoicing/invoices

- mod-invoice-storage/examples/voucher.sample
- mod-invoice-storage/examples/voucher_collection.sample
- mod-invoice-storage/examples/voucher_line.sample
- mod-invoice-storage/examples/voucher_line_collection.sample
- mod-invoice-storage/schemas/voucher.json
- mod-invoice-storage/schemas/voucher_collection.json
- mod-invoice-storage/schemas/voucher_line.json
- mod-invoice-storage/schemas/voucher_line_collection.json
https://issues.folio.org/browse/MODINVOSTO-9
Added new schema as per current sheet: https://docs.google.com/spreadsheets/d/1F88PoSnEKD7oFnza1ZuOgzAgKnK95XOyTQzxyww3tZA/edit#gid=1784784202
As the fields are still under discussion, this is the first draft, the schema can change.
Ideally all of the PRs involved in breaking changes would be merged in the …
> MODINVSTO-9- vouchers schemas and examples

- mod-orgs/examples/contact_collection.sample
- mod-orgs/examples/contact_get.sample
- mod-orgs/examples/contact_post.sample
- mod-orgs/schemas/contact.json
https://issues.folio.org/browse/MODORGS-27 - "Add default value for inactive"
Added the default vale
modified the sample files
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
> MODORGS-27 - adding default inactive property

- mod-invoice-storage/examples/voucher_line.sample
- mod-invoice-storage/schemas/voucher_line_collection.json
Correcting the missing required fields in sample and correcting the typo
> MODINVSTO-11 Invoice Lines CRUD

- mod-orders-storage/examples/po_line_collection.sample
- mod-orders-storage/examples/po_line_get.sample
- mod-orders-storage/examples/po_line_post.sample
- mod-orders-storage/examples/purchase_order_collection.sample
- mod-orders-storage/examples/purchase_order_get.sample
- mod-orders-storage/schemas/po_line.json
- mod-orders-storage/schemas/purchase_order.json
- mod-orders/examples/composite_po_line.sample
- mod-orders/examples/composite_purchase_order.sample
- mod-orders/schemas/composite_po_line.json
- mod-orders/schemas/composite_purchase_order.json
[MODORDERS-237](https://issues.folio.org/browse/MODORDERS-237)/[MODORDSTOR-76](https://issues.folio.org/browse/MODORDSTOR-76) Move "Owner" field to PO level
Updating PO and PO Lines schemas for both modules moving `owner` to PO level
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
> MODORDERS-237/MODORDSTOR-76 Move "Owner" field to PO level

- mod-orgs/examples/interface_collection.sample
- mod-orgs/examples/interface_get.sample
- mod-orgs/examples/interface_post.sample
- mod-orgs/schemas/interface.json
- mod-orgs/schemas/interface_type.json
[MODORGS-28](https://issues.folio.org/browse/MODORGS-28) Add field `type` to interface.json schema
- adding interface_type.json schema
- adding field type to interface.json as array of interface_type
- updating samples
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
> MODORGS-28 Interface schema update: new field - type

- mod-finance/examples/encumbrance.sample
- mod-finance/examples/encumbrance_collection.sample
- mod-finance/schemas/encumbrance.json
- mod-finance/schemas/encumbrance_collection.json
https://issues.folio.org/browse/MODFISTO-10
* Updated encumbrance schema and examples.
* Merge when mod-finance-storage is ready. …
> MODFISTO-10 Updated encumbrance schema and examples

- mod-orders-storage/examples/po_line_collection.sample
- mod-orders-storage/examples/po_line_get.sample
- mod-orders-storage/examples/po_line_post.sample
- mod-orders-storage/schemas/fund_distribution.json
- mod-orders/examples/composite_po_line.sample
- mod-orders/examples/composite_purchase_order.sample
[MODORDERS-242](https://issues.folio.org/browse/MODORDERS-242) PoLine FundDistribution schema updates
Updating schema and samples according to requirements
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …
> MODORDERS-242 PoLine FundDistribution schema updates

- mod-orders-storage/examples/purchase_order_collection.sample
- mod-orders-storage/examples/purchase_order_get.sample
- mod-orders-storage/examples/purchase_order_post.sample
- mod-orders-storage/schemas/purchase_order.json
- mod-orders/examples/composite_purchase_order.sample
- mod-orders/examples/composite_purchase_orders.sample
- mod-orders/schemas/composite_purchase_order.json
https://issues.folio.org/browse/MODORDERS-253
* Added `billTo` and `shipTo` properties to purchase order schema and examples …
> MODORDERS-253 Purchase order: bill to and ship to addresses

- mod-invoice-storage/schemas/invoice.json
[MODINVOICE-42](https://issues.folio.org/browse/MODINVOICE-42) Invoice schema update
Making `subTotal` non-readonly due to [RMB-384](https://issues.folio.org/browse/RMB-384)
> MODINVOICE-42 Invoice schema updates

- mod-finance/examples/budget.sample
- mod-finance/examples/budget_collection.sample
- mod-finance/examples/fiscal_year.sample
- mod-finance/examples/fiscal_year_collection.sample
- mod-finance/examples/fund_distribution.sample
- mod-finance/examples/fund_distribution_collection.sample
- mod-finance/examples/ledger.sample
- mod-finance/examples/ledger_collection.sample
- mod-finance/examples/transaction.sample
- mod-finance/examples/transaction_collection.sample
- mod-finance/schemas/budget.json
- mod-finance/schemas/budget_collection.json
- mod-finance/schemas/fiscal_year.json
- mod-finance/schemas/fiscal_year_collection.json
- mod-finance/schemas/fund_distribution.json
- mod-finance/schemas/fund_distribution_collection.json
- mod-finance/schemas/ledger.json
- mod-finance/schemas/ledger_collection.json
- mod-finance/schemas/transaction.json
- mod-finance/schemas/transaction_collection.json
[MODFISTO-8](https://issues.folio.org/browse/MODFISTO-8) refactor finance schemas
- removing `first` and `last` properties from collection schemas
- use camel case for schema properties
- changing uuid pattern to more strict one
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
> MODFISTO-8 finance schema updates

- mod-finance/examples/fund.sample
- mod-finance/examples/fund_collection.sample
- mod-finance/schemas/fund.json
- mod-finance/schemas/fund_collection.json
[MODFISTO-8](https://issues.folio.org/browse/MODFISTO-8) Fund Schema Updates
Updating fund schemas according to requirements from jira ticket
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …
> MODFISTO-8 Fund Schema Updates

- mod-invoice-storage/examples/adjustment.sample
- mod-invoice-storage/examples/invoice.sample
- mod-invoice-storage/examples/invoice_collection.sample
- mod-invoice-storage/examples/invoice_line.sample
- mod-invoice-storage/examples/invoice_line_collection.sample
- mod-invoice-storage/schemas/adjustment.json
https://issues.folio.org/browse/MODINVOICE-53 - Adjustment schema changes
1. Rename fields
2. Modify examples …
> MODINVOICE-53- Adjustment schema changes

- mod-orders-storage/examples/order_invoice_relationship_collection.sample
- mod-orders-storage/examples/order_invoice_relationship_post.sample
- mod-orders-storage/schemas/order_invoice_relationship.json
- mod-orders-storage/schemas/order_invoice_relationship_collection.json
Models for CRUD operations for relationship between order and invoice
While it's helpful …
> MODORDSTOR-80 Models for CRUD operation for relationship between order and invoice

- mod-orders-storage/examples/purchase_order_collection.sample
- mod-orders-storage/examples/purchase_order_get.sample
- mod-orders-storage/schemas/purchase_order.json
- mod-orders/examples/composite_purchase_order.sample
- mod-orders/schemas/composite_purchase_order.json
Rename owner to acquisitionsUnit
While it's helpful for reviewers to help identify …
> MODORDSTOR-81 Rename owner to acquisitionsUnit

- mod-orders-storage/examples/purchase_order_collection.sample
- mod-orders-storage/examples/purchase_order_get.sample
- mod-orders-storage/schemas/purchase_order.json
- mod-orders/examples/composite_purchase_order.sample
- mod-orders/schemas/composite_purchase_order.json
Revert changes for [MODORDSTOR-81](https://issues.folio.org/browse/MODORDSTOR-81)
Revert changes done in scope of https://github.com/folio-org/acq-models/pull/140.
> Revert PR #140 - MODORDSTOR-81

- mod-orders-storage/schemas/po_line.json
- mod-orders/schemas/composite_po_line.json
Make purchase order id required.
While it's helpful for reviewers to help identify …
> MODORDSTOR-90 make purchase order id required

- mod-finance/examples/fiscal_year.sample
- mod-finance/examples/fiscal_year_collection.sample
- mod-finance/schemas/fiscal_year.json
https://issues.folio.org/browse/MODFUND-50
* Make fiscal year `startDate` and `endDate` required
* Make `code` not required
* Update examples
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …
> MODFUND-50 update fiscal year properties

- mod-orders-storage/examples/acquisitions_unit_collection.sample
- mod-orders-storage/examples/acquisitions_unit_get.sample
- mod-orders-storage/examples/acquisitions_unit_post.sample
- mod-orders-storage/examples/order_invoice_relationship_collection.sample
- mod-orders-storage/schemas/acquisitions_unit.json
- mod-orders-storage/schemas/acquisitions_unit_collection.json
Create schemes for implementation CRUD operations for acquisitions unit.
While it's …
> MODORDSTOR-82 Create schemes and examples for acquisitions unit.

- mod-finance/examples/fund.sample
- mod-finance/examples/fund_collection.sample
- mod-finance/schemas/fund.json
https://issues.folio.org/browse/MODFISTO-14
Remove fund.acquisitionsUnit
While it's …
> MODFISTO-14 remove fund.acquisitionsUnit

- mod-orders-storage/examples/purchase_order_collection.sample
- mod-orders-storage/examples/purchase_order_get.sample
- mod-orders-storage/examples/purchase_order_post.sample
- mod-orders-storage/schemas/purchase_order.json
- mod-orders/examples/composite_purchase_order.sample
- mod-orders/examples/composite_purchase_orders.sample
- mod-orders/schemas/composite_purchase_order.json
https://issues.folio.org/browse/MODORDERS-267
* added template property
* examples updated …
> MODORDERS-267 added template property to PO.

- mod-invoice-storage/schemas/invoice_line.json
https://issues.folio.org/browse/MODINVOICE-75
* made fundDistributions not required for invoice lines …
> MODINVOICE-75 made fundDistributions not required for invoice lines

- mod-invoice-storage/examples/invoice_line_collection.sample
- mod-invoice-storage/schemas/invoice_line.json
* PR is to remove restriction missed last time
* removed fundDistributions `minItems=1` restriction for invoice line schema  …
> MODINVOICE-75 removed unnecessary restriction

- mod-orgs/examples/address_collection.sample
- mod-orgs/examples/address_get.sample
- mod-orgs/examples/category_collection.sample
- mod-orgs/examples/category_get.sample
- mod-orgs/examples/contact_collection.sample
- mod-orgs/examples/contact_get.sample
- mod-orgs/examples/email_collection.sample
- mod-orgs/examples/email_get.sample
- mod-orgs/examples/interface_collection.sample
- mod-orgs/examples/interface_credential_get.sample
- mod-orgs/examples/interface_get.sample
- mod-orgs/examples/organization_collection.sample
- mod-orgs/examples/organization_get.sample
- mod-orgs/examples/organization_put.sample
- mod-orgs/examples/phone_number_collection.sample
- mod-orgs/examples/phone_number_get.sample
- mod-orgs/examples/url_collection.sample
- mod-orgs/examples/url_get.sample
- mod-orgs/schemas/address.json
- mod-orgs/schemas/category.json
- mod-orgs/schemas/contact.json
- mod-orgs/schemas/email.json
- mod-orgs/schemas/interface.json
- mod-orgs/schemas/interface_credential.json
- mod-orgs/schemas/organization.json
- mod-orgs/schemas/phone_number.json
- mod-orgs/schemas/url.json
[MODORGS-32](https://issues.folio.org/browse/MODORGS-32)
Change JSON schemas
While it's …
> MODORGS-32 change JSON schemas

- mod-orders-storage/examples/po_line_collection.sample
- mod-orders-storage/examples/po_line_get.sample
- mod-orders-storage/examples/po_line_post.sample
- mod-orders-storage/examples/purchase_order_collection.sample
- mod-orders-storage/examples/purchase_order_get.sample
- mod-orders-storage/examples/purchase_order_post.sample
- mod-orders-storage/schemas/po_line.json
- mod-orders-storage/schemas/purchase_order.json
- mod-orders/examples/composite_po_line.sample
- mod-orders/examples/composite_purchase_order.sample
- mod-orders/schemas/composite_po_line.json
- mod-orders/schemas/composite_purchase_order.json
We need to implement assignment of tags and search by tags in Orders app.
Add tags attribute to order object, so that tags can be assigned to orders.
This will also allow us to search order by tags by using CQL query. (e.g. "limit=30&query= tags.tagList=important" will return orders with tag "important"  )
Change tags in order lines to reference raml-util/schemas/tags.schema
ui-order doesn't use this attribute (https://github.com/folio-org/ui-orders/search?q=tags&unscoped_q=tags) so this shouldn't be a breaking change
- What …
> MODTAG-25 Add tags to records

- mod-invoice-storage/examples/invoice.sample
- mod-invoice-storage/examples/invoice_collection.sample
- mod-invoice-storage/examples/invoice_line.sample
- mod-invoice-storage/examples/invoice_line_collection.sample
- mod-invoice-storage/schemas/invoice.json
- mod-invoice-storage/schemas/invoice_line.json
We need to implement assignment of tags and search by tags in Invoice app.
Add tags attribute to invoice object, so that tags can be assigned to invoices.
This will also allow us to search invoice by tags by using CQL query. (e.g. "limit=30&query= tags.tagList=important" will return invoices with tag "important" )
Ideally all of the PRs involved in …
> MODINVOICE-79 Add tags to invoices and invoice-lines

- mod-invoice-storage/examples/invoice.sample
- mod-invoice-storage/examples/invoice_collection.sample
- mod-invoice-storage/examples/invoice_line.sample
- mod-invoice-storage/examples/invoice_line_collection.sample
- mod-invoice-storage/schemas/invoice.json
- mod-invoice-storage/schemas/invoice_line.json
[MODINVOICE-77](https://issues.folio.org/browse/MODINVOICE-77) Make necessary changes to the schemes for invoice and invoiceLine.
- adding `accountingCode` and `accountingNumber` to invoice line schema
- making `source` an enum instead of uuid in invoice.json
- adding required field  `accountingCode` to invoice.json
Ideally all of the PRs involved in …
> MODINVOICE-77 Invoice and invoiceLine schema updates

- mod-orgs/examples/organization_collection.sample
- mod-orgs/examples/organization_get.sample
- mod-orgs/examples/organization_post.sample
- mod-orgs/examples/organization_put.sample
- mod-orgs/schemas/organization.json
We need to implement assignment of tags and search by tags in Organization app.
Add tags attribute to organizations object, so that tags can be assigned to organizations.
This will also allow us to search organization by tags by using CQL query. (e.g. "limit=30&query= tags.tagList=important" will return organizations with tag "important" )
Ideally all of …
> MODORGS-35 Organizations app: Ability to assign tags to an organization record

- mod-finance/examples/budget.sample
- mod-finance/examples/budget_collection.sample
- mod-finance/examples/fiscal_year.sample
- mod-finance/examples/fiscal_year_collection.sample
- mod-finance/examples/fund_distribution.sample
- mod-finance/examples/fund_distribution_collection.sample
- mod-finance/examples/ledger.sample
- mod-finance/examples/ledger_collection.sample
- mod-finance/examples/transaction.sample
- mod-finance/examples/transaction_collection.sample
- mod-finance/schemas/budget.json
- mod-orders/examples/composite_po_line.sample
[MODFISTO-24](https://issues.folio.org/browse/MODFISTO-24) Update Budget Schema
While …
> MODFISTO-24 Update Budget Schema

- mod-finance/examples/group.sample
- mod-finance/examples/group_collection.sample
- mod-finance/examples/group_fund_fiscal_year.sample
- mod-finance/examples/group_fund_fiscal_year_collection.sample
- mod-finance/schemas/group.json
- mod-finance/schemas/group_collection.json
- mod-finance/schemas/group_fund_fiscal_year.json
- mod-finance/schemas/group_fund_fiscal_year_collection.json
[MODFISTO-22](https://issues.folio.org/browse/MODFISTO-22) Create Group schemas
Defining schemas and adding samples
> MODFISTO-22 Create Group schemas

- mod-finance/examples/fiscal_year.sample
- mod-finance/examples/fiscal_year_collection.sample
- mod-finance/schemas/fiscal_year.json
[MODFISTO-25](https://issues.folio.org/browse/MODFISTO-25) Update FiscalYear schema
Updating schemas and samples
> MODFISTO-25 Update FiscalYear schema

- mod-orders-storage/examples/order_template_collection.sample
- mod-orders-storage/examples/order_template_get.sample
- mod-orders-storage/examples/order_template_post.sample
- mod-orders-storage/schemas/order_template.json
- mod-orders-storage/schemas/order_template_collection.json
[MODORDSTOR-106](https://issues.folio.org/browse/MODORDSTOR-106) - Create order-templates API
Schemas for order-templates API.
order_template/order_template_collection schemas added
> MODORDSTOR-106 - Create order-templates API

- mod-orders-storage/examples/po_line_collection.sample
- mod-orders-storage/examples/po_line_get.sample
- mod-orders-storage/examples/po_line_post.sample
- mod-orders-storage/schemas/details.json
- mod-orders/examples/composite_po_line.sample
- mod-orders/examples/composite_purchase_order.sample
[MODORDSTOR-108](https://issues.folio.org/browse/MODORDSTOR-108) Add qualifier field to `poLine->details->productIds[]`
Updating the schqma and samples
> MODORDSTOR-108 Add qualifier field

- mod-finance/examples/fiscal_year.sample
- mod-finance/examples/fiscal_year_collection.sample
- mod-finance/examples/ledger.sample
- mod-finance/examples/ledger_collection.sample
- mod-finance/schemas/fiscal_year.json
- mod-finance/schemas/ledger.json
https://issues.folio.org/browse/MODFISTO-49
- Update fiscal_year schema and sample with `code` and `series`
- Update ledger schema and sample with `fiscalYearOneId`
If schema changes look then I will create PR for mod-finance-storage.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
> Ledger and LedgerFY Schema updates

- mod-finance/schemas/composite_fund.json
[MODFIN-77](https://issues.folio.org/browse/MODFIN-77)
[MODFIN-76](https://issues.folio.org/browse/MODFIN-76) Make fund required for compositeFund …
> MODFIN-77 Make fund required for compositeFund

- mod-finance/examples/group_fund_fiscal_year.sample
- mod-finance/examples/group_fund_fiscal_year_collection.sample
- mod-finance/schemas/group_fund_fiscal_year.json
[MODFISTO-48](https://issues.folio.org/browse/MODFISTO-48) Adjustments to allow listing budgets by group/fiscalYear/ledger
- adding budgetId to group_fund_fiscal_year schema …
> MODFISTO-48 Adjustments to allow listing budgets by group/fiscalYear/ledger

- mod-finance/examples/transaction.sample
- mod-finance/examples/transaction_collection.sample
- mod-finance/schemas/transaction.json
[MODFISTO-46](https://issues.folio.org/browse/MODFISTO-46) Add new field `transaction.sourceInvoiceLineId` …
> MODFISTO-46 Update transaction schema

- mod-finance/examples/transaction_collection.sample
- mod-finance/schemas/encumbrance.json
https://issues.folio.org/browse/MODFISTO-54
-add new fields to encumbrance schema and make them required
orderType
subscription
reEncumber
sourcePurchaseOrderId
sourcePoLineId …
> MODFISTO-54- Encumbrance Schema Updates

- mod-finance/examples/group_fiscal_year_summary.sample
- mod-finance/examples/group_fiscal_year_summary_collection.sample
- mod-finance/examples/group_fund_fiscal_year.sample
- mod-finance/examples/group_fund_fiscal_year_collection.sample
- mod-finance/schemas/group_fiscal_year_summary.json
- mod-finance/schemas/group_fiscal_year_summary_collection.json
- mod-finance/schemas/group_fund_fiscal_year.json
https://issues.folio.org/browse/MODFISTO-50
- Create new `group_fiscal_year_summary` schema and sample
- Update existing schema `group_fund_fiscal_year` and samples
If schema changes look then I will create PR for mod-finance-storage.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
> MODFISTO-50 GroupFiscalYearSummary Schema changes

- mod-orders-storage/schemas/po_line.json
- mod-orders-storage/schemas/purchase_order.json
- mod-orders/schemas/composite_po_line.json
- mod-orders/schemas/composite_purchase_order.json
- mod-orders/schemas/po_number.json
https://issues.folio.org/browse/MODORDERS-334
* update poNumber and poLineNumber patterns …
> MODORDERS-334 updated poNumber pattern

- mod-invoice-storage/schemas/adjustment.json
- mod-invoice-storage/schemas/fund_distribution.json
- mod-invoice-storage/schemas/invoice.json
- mod-invoice-storage/schemas/invoice_line.json
- mod-invoice-storage/schemas/voucher.json
- mod-invoice-storage/schemas/voucher_line.json
- mod-orders-storage/schemas/receiving_history.json
https://issues.folio.org/browse/MODINVOICE-116
* updated poNumbers pattern
* removed repeatable declaration of the uuid pattern
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
> MODINVOICE-116 Update purchase order number pattern

- mod-finance/schemas/budget.json
- mod-finance/schemas/encumbrance.json
[MODFIN-73](https://issues.folio.org/browse/MODFIN-73) - Implement the GET /finance/group-fiscal-year-summaries API
To prevent additional validation of allocated, available, unavailable are nulls in scope of logic introduced [PR#22](https://github.com/folio-org/mod-finance/pull/22).
Make allocated, available, unavailable default values 0.
Ideally all of …
> MODFIN-73 - Implement the GET /finance/group-fiscal-year-summaries API

- mod-orders/schemas/composite_purchase_order.json
[MODORDERS-299](https://issues.folio.org/browse/MODORDERS-299?focusedCommentId=66435&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-66435) 
- making reEncumber default: false for composite order schema according to simple schema …
> MODORDERS-299 Re-integrate with encumbrance API

- mod-finance/schemas/ledger.json
- mod-finance/schemas/ledgerFY.json
[MODFISTO-71](https://issues.folio.org/browse/MODFISTO-71) Make numbers default=0
While …
> MODFISTO-71 Persist totals to ledgerFY table

- mod-orgs/examples/organization_post.sample
- mod-orgs/schemas/address.json
- mod-orgs/schemas/category.json
- mod-orgs/schemas/contact.json
- mod-orgs/schemas/email.json
- mod-orgs/schemas/interface.json
- mod-orgs/schemas/interface_credential.json
- mod-orgs/schemas/organization.json
- mod-orgs/schemas/phone_number.json
- mod-orgs/schemas/url.json
https://issues.folio.org/browse/MODORGS-56
* isVendor default = false
* updated UUIDs pattern for mod-orgs
* example updated …
> MODORGS-56 set isVendor default = false

- mod-orders/examples/checkinCollection.sample
- mod-orders/examples/receivingCollection.sample
- mod-orders/schemas/checkinCollection.json
- mod-orders/schemas/receivingCollection.json
https://issues.folio.org/browse/MODORDERS-340
- Update receiving and checkin schemas
- Update examples
Example of call number: https://www.lib.sfu.ca/find/what-call-number
If the changes look good then I will start working on mod-orders-storage and mod-orders …
> MODORDERS-340: Add call number while receiving and checkin

- mod-finance/examples/ledger.sample
- mod-finance/examples/ledger_collection.sample
- mod-finance/schemas/ledger.json
https://issues.folio.org/browse/MODFISTO-64
https://wiki.folio.org/display/FOLIJET/Finance+Data+Model#FinanceDataModel-TransactionRestrictions
* added required fields …
> MODFISTO-64 update ledger schema

- mod-orders-storage/examples/piece_collection.sample
- mod-orders-storage/examples/piece_get.sample
- mod-orders-storage/examples/piece_post.sample
- mod-orders-storage/examples/receiving_history_collection.sample
- mod-orders-storage/examples/receiving_history_get.sample
- mod-orders-storage/schemas/piece.json
- mod-orders-storage/schemas/receiving_history.json
[MODORDERS-350](https://issues.folio.org/browse/MODORDERS-350) 
- adding receiptDate to piece and receiving schemes
- making receiptDate required for piece
- updating samples …
> MODORDERS-350 Update piece schema (receipt date)

- mod-orders-storage/examples/po_line_collection.sample
- mod-orders-storage/examples/po_line_get.sample
- mod-orders-storage/examples/po_line_post.sample
- mod-orders-storage/schemas/po_line.json
- mod-orders/examples/composite_po_line.sample
- mod-orders/examples/composite_purchase_order.sample
- mod-orders/examples/composite_purchase_orders.sample
- mod-orders/schemas/composite_po_line.json
https://issues.folio.org/browse/MODORDERS-346
* updated poLine schemas and examples …
> MODORDERS-346 # updated poLines schemas and examples

- mod-orders/schemas/checkinCollection.json
- mod-orders/schemas/item_status.json
- mod-orders/schemas/receivingCollection.json
In addition to PR https://github.com/folio-org/acq-models/pull/216
> MODORDERS-353 - Migrate to new major version of item-storage, inventory, circulation

- mod-invoice-storage/examples/batch_group_collection.sample
[MODINVOSTO-50](https://issues.folio.org/browse/MODINVOSTO-50) - Create batch-group CRUD API
Create sample batch group collection
Sample batch group collection created …
> MODINVOSTO-50 - Create batch-group CRUD API

- mod-invoice-storage/examples/export_configuration_collection.sample
- mod-invoice-storage/schemas/export_configuration.json
- mod-invoice-storage/schemas/export_configuration_collection.json
When implementing the schemas for this we missed the export_config_collection schema.  Also included here are several other minor changes such as adjustments to the export_configuration->uploadURI regex pattern
* Add the missing collection schema/example
* Adjust the uploadURI pattern as needed
Ideally all of the PRs involved in breaking changes would be …
> MODINVOSTO-51 - Schema updates for Batch Voucher Export Config API

- mod-orders-storage/examples/purchase_order_get.sample
- mod-orders-storage/examples/purchase_order_post.sample
- mod-orders-storage/schemas/ongoing.json
- mod-orders-storage/schemas/reason_for_closure.json
[MODORDSTOR-137](https://issues.folio.org/browse/MODORDSTOR-137) Add `notes` and `reviewDate` to ongoing schema …
> MODORDSTOR-137 Add fields to ongoing schema

- mod-finance/examples/awaiting_payment.sample
- mod-finance/schemas/awaiting_payment.json
[MODFIN-113](https://issues.folio.org/browse/MODFIN-113)  …
> MODFIN-113 Add invoiceId and invoiceLineId to the awaitingPayment schema

- mod-invoice-storage/examples/batch_voucher_export.sample
- mod-invoice-storage/examples/batch_voucher_export_collection.sample
- mod-invoice-storage/schemas/batch_voucher_export_collection.json
[MODINVOSTO-54](https://issues.folio.org/browse/MODINVOSTO-54) - Create batch-voucher-exports CRUD API
Batch voucher export collection schema and sample.
Batch voucher export collection schema and sample added.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
> MODINVOSTO-54 - Create batch-voucher-exports CRUD API

- mod-finance/schemas/budget.json
https://issues.folio.org/browse/MODFISTO-84
* Remove default values
While it's helpful …
> MODFISTO-84 Remove default value

- mod-finance/schemas/invoice_transaction_summary.json
- mod-finance/schemas/order_transaction_summary.json
https://issues.folio.org/browse/MODFISTO-87
* added isProcessed field to transaction summaries schemas which indicates "all or nothing" operation is completed. …
> MODFISTO-87 updated transactions summary schema

- mod-finance/schemas/invoice_transaction_summary.json
- mod-finance/schemas/order_transaction_summary.json
https://issues.folio.org/browse/MODFISTO-95
* the field "isProcessed" is not needed anymore
* removed unused fields …
> MODFISTO-95 removed unused fields

- common/schemas/currency_code.json
- common/schemas/floating_point_string.json
- mod-finance/examples/exchange_rate.sample
- mod-finance/schemas/exchange_rate.json
[MODFIN-111](https://issues.folio.org/browse/MODFIN-111) - Exchange rate API
Exchange rate schema and example
Exchange rate schema and example created …
> Modfin 111 - Exchange rate API

- mod-finance/examples/exchange_rate.sample
- mod-finance/schemas/exchange_rate.json
[MODFIN-111](https://issues.folio.org/browse/MODFIN-111) - Exchange rate API
Create an API for obtaining an exchangeRate between two currencies.
* changed exchangeRate type (string -> number)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
> MODFIN-111 - Exchange rate API

- common/examples/message.sample
- common/schemas/message.json
[MODORGS-137](https://issues.folio.org/browse/MODINVOICE-1371) - Implement "test" endpoint. 
Ability to return free-text message as JSON .
* add message.json
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …
> [MODORGS-137] - Implement "test" endpoint. Add free text message type.

- mod-invoice-storage/examples/adjustment.sample
- mod-invoice-storage/examples/batch_voucher.sample
- mod-invoice-storage/examples/invoice.sample
- mod-invoice-storage/examples/invoice_collection.sample
- mod-invoice-storage/examples/invoice_line.sample
- mod-invoice-storage/examples/invoice_line_collection.sample
- mod-invoice-storage/schemas/adjustment.json
- mod-invoice-storage/schemas/batched_voucher.json
- mod-invoice-storage/schemas/invoice.json
https://issues.folio.org/browse/MODINVOSTO-58
* schemas and examples updated
While it's …
> MODINVOSTO-58 schemas update

- mod-finance/examples/transaction.sample
- mod-finance/examples/transaction_allocation.sample
- mod-finance/examples/transaction_collection.sample
- mod-finance/examples/transaction_credit.sample
- mod-finance/examples/transaction_encumbrance.sample
- mod-finance/examples/transaction_payment.sample
- mod-finance/examples/transaction_transfer.sample
- mod-finance/schemas/transaction.json
[MODFISTO-85](https://issues.folio.org/browse/MODFISTO-85) - Update the transaction 'source' enum
We need to make a few tweaks to the transaction schema, namely the "source" field enumeration.
New values:
* User
* FiscalYear
* PoLine
* Invoice
Transaction schema and examples are updated
Ideally all of the PRs involved in breaking changes would be merged …
> MODFISTO-85 - Update the transaction 'source' enum

- mod-orders-storage/examples/po_line_collection.sample
- mod-orders-storage/examples/po_line_get.sample
- mod-orders-storage/examples/po_line_post.sample
- mod-orders-storage/schemas/po_line.json
https://issues.folio.org/browse/MODORDSTOR-145
* added instanceId to poline schema
While …
> Modordstor 145 Create title with populated instanceId upon creation of poLine

- mod-orders-storage/examples/title_collection.sample
- mod-orders-storage/examples/title_get.sample
- mod-orders-storage/schemas/po_line.json
- mod-orders-storage/schemas/title.json
[MODORDSTOR-136](https://issues.folio.org/browse/MODORDSTOR-136) …
> MODORDSTOR-136 Title, PoLine schema updates

- mod-finance/schemas/encumbrance.json
* https://issues.folio.org/browse/MODFISTO-109
* added new encubrance status value
While …
> MODFISTO-109 added encumbrance status value "Pending"

- mod-finance/schemas/order_transaction_summary.json
- mod-orders-storage/schemas/prefix.json
- mod-orders-storage/schemas/purchase_order.json
- mod-orders-storage/schemas/reason_for_closure.json
- mod-orders-storage/schemas/suffix.json
* PgUtils.put() fails because of https://issues.folio.org/browse/RMB-628
* added id field for child objects …
> RMB-628 workaround for PgUtils.put() failure

- mod-invoice-storage/schemas/voucher.json
https://issues.folio.org/browse/MODINVOICE-172
* make voucher.accountingCode no required …
> MODINVOICE-172 make voucher.accountingCode no required

- mod-finance/examples/expense_class.sample
- mod-finance/examples/expense_class_collection.sample
- mod-finance/schemas/expense_class.json
- mod-finance/schemas/expense_class_collection.json
- mod-finance/schemas/transaction.json
- mod-invoice-storage/examples/invoice_line.sample
- mod-orders-storage/schemas/fund_distribution.json
- mod-orders/examples/composite_purchase_order.sample
https://issues.folio.org/browse/MODFISTO-104
* added expense_class schema and examples
* transaction schema updated …
> MODFISTO-104 added expense_class schema

- mod-invoice-storage/schemas/fund_distribution.json
https://issues.folio.org/browse/MODINVOSTO-71
* extended fundDistribution schema
While …
> MODINVOSTO-71 extended fundDistribution schema

- mod-finance/examples/budget.sample
- mod-finance/examples/ledger.sample
- mod-finance/examples/ledgerFY.sample
- mod-finance/schemas/budget.json
- mod-finance/schemas/ledger.json
- mod-finance/schemas/ledgerFY.json
* https://issues.folio.org/browse/MODFISTO-102
* added netTransfers support
While it's …
> MODFISTO-102 added netTransfers support

- mod-finance/examples/shared_budget.sample
- mod-finance/schemas/budget.json
- mod-finance/schemas/shared_budget.json
- mod-finance/schemas/status_expense_class.json
[MODFIN-138](https://issues.folio.org/browse/MODFIN-138)
Created shared_budget.json schema extended from budget.json …
> MODFIN-138 Update /finance/budgets POST and PUT API

- mod-finance/examples/group_expense_class_totals.sample
- mod-finance/examples/group_expense_class_totals_collection.sample
- mod-finance/examples/shared_budget.sample
- mod-finance/schemas/budget_expense_class_totals_collection.json
- mod-finance/schemas/group_expense_class_totals.json
- mod-finance/schemas/group_expense_class_totals_collection.json
[MODFIN-137](https://issues.folio.org/browse/MODFIN-137) …
> MODFIN-137 Define and implement GET /finance/groups/id/expense-classes-totals API

- mod-orgs/examples/organization_collection.sample
- mod-orgs/examples/organization_get.sample
- mod-orgs/examples/organization_post.sample
- mod-orgs/examples/organization_put.sample
- mod-orgs/schemas/organization.json
https://issues.folio.org/browse/MODORGSTOR-77
* added exportToAccounting field
While …
> MODORGSTOR-77 added exportToAccounting field

- mod-finance/schemas/invoice_transaction_summary.json
- mod-finance/schemas/order_transaction_summary.json
[MODFISTO-138](https://issues.folio.org/browse/MODFISTO-138) to be able use PgUtils.put method
- removed extends from entity
- added id field to invoice_transaction_summary schema
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
> MODFISTO-138 Update PUT /finance-storage/transactions/id to support allOrNothing for Pending payments

- mod-finance/examples/group_expense_class_totals.sample
- mod-finance/examples/group_expense_class_totals_collection.sample
- mod-finance/schemas/group_expense_class_totals.json
[MODFIN-161](https://issues.folio.org/browse/MODFIN-161) …
> MODFIN-161 Add fields to the group expense classes schema

- mod-invoice-storage/schemas/invoice.json
- mod-orders-storage/schemas/po_line.json
- mod-orders-storage/schemas/purchase_order.json
- mod-orders/schemas/composite_po_line.json
- mod-orders/schemas/composite_purchase_order.json
https://issues.folio.org/browse/MODORDSTOR-197 - Adding certain prefix and suffixes prevents user from being able to save
Schema changed …
> [MODORDSTOR-197] - Increase limit for poNumber

- mod-invoice-storage/schemas/invoice.json
https://issues.folio.org/browse/MODINVOSTO-96
Add default value to readOnly : "total" and "subTotal" …
> [MODINVOSTO-96] - add default value 0

- mod-invoice-storage/schemas/invoice.json
> [MODINVOSTO-96] - delete default value

- mod-invoice-storage/schemas/invoice.json
- mod-orders/examples/item_summary.sample
- mod-orders/schemas/item_summary.json
Define "item summary" model for the acquisition accordion in inventory > https://issues.folio.org/browse/MODORDSTOR-201 …
> Modordstor 201

- mod-orders/schemas/composite_purchase_order.json
https://issues.folio.org/browse/MODORDSTOR-184
Added rolloverStatus field
While it's …
> [MODORDSTOR-184] Added rolloverStatus field

- mod-finance/examples/budget_rollover.sample
- mod-finance/examples/encumbrance_rollover.sample
- mod-finance/examples/ledger_fiscal_year_rollover.sample
- mod-finance/examples/ledger_fiscal_year_rollover_collection.sample
- mod-finance/schemas/budget_rollover.json
- mod-finance/schemas/encumbrance_rollover.json
- mod-finance/schemas/ledger_fiscal_year_rollover.json
- mod-finance/schemas/ledger_fiscal_year_rollover_collection.json
[MODFISTO-164](https://issues.folio.org/browse/MODFISTO-164)
Created ledger FY rollover models with samples:
- ledger_fiscal_year_rollover.json
- ledger_fiscal_year_rollover_collection.json
- encumbrance_rollover.json
- budget_rollover.json
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
> MODFISTO-164 Define model and schema of the fiscal year rollover for Ledger

- mod-finance/examples/ledger_fiscal_year_rollover_error.sample
- mod-finance/examples/ledger_fiscal_year_rollover_error_collection.sample
- mod-finance/schemas/fund_rollover_error_details.json
- mod-finance/schemas/ledger_fiscal_year_rollover_error.json
- mod-finance/schemas/ledger_fiscal_year_rollover_error_collection.json
- mod-finance/schemas/order_rollover_error_details.json
[MODFISTO-175](https://issues.folio.org/browse/MODFISTO-175)
Created ledger FY rollover error models with samples:
ledger_fiscal_year_rollover_error.json
ledger_fiscal_year_rollover_error_collection.json
order_rollover_error_details.json
fund_rollover_error_details.json
https://wiki.folio.org//display/DD/Fiscal+year+rollover#Fiscalyearrollover-ledger_fiscal_year_rollover_error
https://wiki.folio.org//display/DD/Fiscal+year+rollover#Fiscalyearrollover-order_rollover_error_details
https://wiki.folio.org//display/DD/Fiscal+year+rollover#Fiscalyearrollover-fund_rollover_error_details
If there are …
> MODFISTO-175 Define model and schema for the errors of the ledger fiscal year rollover

- mod-finance/examples/transaction_collection.sample
- mod-finance/examples/transaction_encumbrance.sample
- mod-finance/schemas/encumbrance.json
[MODFISTO-194](https://issues.folio.org/browse/MODFISTO-194)
Add order status to encumbrance schema
- update schema with orderStatus field …
> MODFISTO-194 Add order status to encumbrance schema

- mod-orders-storage/examples/po_line_collection.sample
https://issues.folio.org/browse/MODORDSTOR-204
Renamed the cancellationRestrictionRote field …
> [MODORDSTOR-204] Renamed the cancellationRestrictionRote field

- mod-finance/examples/fund_type_collection.sample
https://issues.folio.org/browse/MODFISTO-198
Renamed the funds field in the sample
While …
> [MODFISTO-198] Renamed the funds field in the sample

- mod-finance/schemas/budget.json
- mod-finance/schemas/shared_budget.json
https://issues.folio.org/browse/MODFISTO-186
Updated budget and shared_budget schemas in the acq-modules …
> [MODFISTO-186] Updated budget and shared_budget schemas

- mod-finance/schemas/budget.json
- mod-finance/schemas/shared_budget.json
Signed-off-by: Yauheni Kuzmianok <yauheni_kuzmianok@epam.com> …
> MODFISTO-186 Update budget and shared_budget fields

- mod-invoice-storage/examples/invoice.sample
- mod-invoice-storage/schemas/invoice.json
https://issues.folio.org/browse/MODINVOSTO-89 > Capture date paid in invoice schema
https://issues.folio.org/browse/MODINVOSTO-92 > Add field "accountNo" for supporting vendors that have more than one account
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …
> Modinvosto 89,92

- mod-orders-storage/examples/po_line_collection.sample
- mod-orders-storage/examples/po_line_get.sample
- mod-orders-storage/examples/po_line_post.sample
- mod-orders-storage/schemas/cost.json
- mod-orders/examples/composite_po_line.sample
- mod-orders/examples/composite_purchase_order.sample
- mod-orders/examples/composite_purchase_orders.sample
https://issues.folio.org/browse/MODORDSTOR-185
* Add field "exchangeRate" to the cost of POL
Pre-Merge Checklist …
> MODORDSTOR-185 

- mod-orders-storage/schemas/payment_status.json
- mod-orders-storage/schemas/receipt_status.json
* https://issues.folio.org/browse/MODORDERS-459
* add ongoing status
While it's helpful …
> MODORDERS-465 add ongoing status

- mod-finance/schemas/budget_rollover.json
Signed-off-by: Yauheni Kuzmianok <yauheni_kuzmianok@epam.com> …
> MODFISTO-210 Add setAllowances field

- mod-finance/schemas/budget_rollover.json
- Make allowable values optional
While it's helpful for reviewers to help identify …
> MODFISTO-210 Make allowable property optional

- mod-finance/schemas/budget_rollover.json
[MODFISTO-217](https://issues.folio.org/browse/MODFISTO-217)
make `rolloverAllocation` and `rolloverAvailable` default false …
> MODFISTO-217 When not checking Rollover or Available in roll settings, systems rolls all amounts

- common/schemas/reference_number_item.json
- common/schemas/reference_numbers.json
- mod-invoice-storage/examples/invoice_line.sample
- mod-invoice-storage/schemas/invoice_line.json
- mod-orders-storage/examples/po_line_collection.sample
- mod-orders-storage/examples/po_line_get.sample
- mod-orders-storage/examples/po_line_post.sample
- mod-orders-storage/schemas/vendor_detail.json
- mod-orders/examples/composite_po_line.sample
- mod-orders/examples/composite_purchase_order.sample
[MODORDSTOR-146](https://issues.folio.org/browse/MODORDSTOR-146)
[MODINVOSTO-81](https://issues.folio.org/browse/MODINVOSTO-81)
- extract refNumber,  refNumberType, vendorDetailsSource to separate schema reference_number_item.json and move to common folder …
> MODORDSTOR-146/MODINVOSTO-81 Support repitable pair of "refNumber" and "refNumberType"

- mod-orders/examples/composite_purchase_order.sample
- mod-orders/schemas/composite_purchase_order.json
[MODORDERS-478](https://issues.folio.org/browse/MODORDERS-478) …
> MODORDERS-478 Total encumbered for PO showing more than one year of encumbrances

- mod-invoice-storage/examples/invoice_line.sample
- mod-invoice-storage/examples/invoice_line_collection.sample
[MODINVOICE-135](https://issues.folio.org/browse/MODINVOICE-135)
Updated examples to remove the invoice number from invoiceLineNumber. …
> [MODINVOICE-135] Updated examples to remove the invoice number from invoiceLineNumber

- mod-invoice-storage/schemas/voucher.json
[MODINVOSTO-106](https://issues.folio.org/browse/MODINVOSTO-106)
Copied the fields `enclosureNeeded` and `accountNo` from the invoice schema to the voucher schema. …
> [MODINVOSTO-106] Added fields enclosureNeeded and accountNo into voucher schema

- mod-invoice-storage/examples/batch_voucher.sample
> [MODINVOSTO-113] - Add filled in "VendorAddress" into batch voucher

- mod-invoice-storage/examples/voucher.sample
- mod-invoice-storage/schemas/voucher.json
https://issues.folio.org/browse/MODINVOSTO-114 …
> MODINVOSTO-114 Add vendor data to voucher schema

- mod-finance/schemas/ledger_fiscal_year_rollover.json
Signed-off-by: Yauheni Kuzmianok <yauheni_kuzmianok@epam.com> …
> MODFISTO-225 Add currency factor field

- mod-invoice-storage/examples/invoice_line.sample
- mod-invoice-storage/examples/invoice_line_collection.sample
https://issues.folio.org/browse/MODINVOSTO-115 …
> [MODINVOSTO-115] - Example API JSON, "invoice_line_collection.sample", has invalid field

- mod-orders-storage/examples/po_line_collection.sample
- mod-orders-storage/examples/po_line_get.sample
- mod-orders-storage/schemas/po_line.json
- mod-orders/examples/composite_po_line.sample
- mod-orders/examples/inventory_order_summary.sample
- mod-orders/schemas/composite_po_line.json
- mod-orders/schemas/inventory_order_summary.json
https://issues.folio.org/browse/MODORDSTOR-200 : Define "inventory order summary" model for the acquisition accordion in inventory …
> Define "inventory order summary" model for the acquisition accordion in inventory

- mod-orders-storage/schemas/po_line.json
- mod-orders/schemas/composite_po_line.json
> [MODORDSTOR-200] - Fix holdingsIds

- mod-orders-storage/schemas/po_line.json
- mod-orders/schemas/composite_po_line.json
https://issues.folio.org/browse/MODORDSTOR-200 …
> [MODORDSTOR-200] - Change holdingIds to Set

- mod-orders-storage/schemas/po_line.json
- mod-orders/schemas/composite_po_line.json
Decided implement it in separate branch   …
> [MODORDSTOR-200] - Rollback changes

- mod-orders-storage/schemas/source.json
https://issues.folio.org/browse/MODEBSNET-10
* extended source enum
While it's helpful …
> MODEBSNET-10 added source EBSCONET value

- mod-finance/examples/fund_code_vs_expense_classes_type.sample
- mod-finance/examples/fund_code_vs_expense_classes_type_collection.sample
- mod-finance/schemas/fund_code_vs_expense_classes_type.json
- mod-finance/schemas/fund_code_vs_expense_classes_type_collection.json
> [MODFISTO-243] - Define DTO schema for combination of fund code and expense class

- mod-orders/examples/checkinCollection.sample
- mod-orders/examples/receivingCollection.sample
- mod-orders/schemas/checkinCollection.json
- mod-orders/schemas/receivingCollection.json
> [MODORDSTOR-235] - Add holdingId to receiving

- mod-finance/examples/transaction.sample
- mod-finance/examples/transaction_collection.sample
- mod-finance/examples/transaction_credit.sample
- mod-finance/examples/transaction_encumbrance.sample
- mod-finance/examples/transaction_payment.sample
- mod-finance/examples/transaction_pending_payment.sample
- mod-finance/schemas/transaction.json
- mod-invoice-storage/examples/voucher.sample
- mod-invoice-storage/schemas/batched_voucher.json
- mod-invoice-storage/schemas/voucher.json
* Cancel invoice : Update voucher and transaction schema with new fields
* added Canceled status to the voucher schema
* added invoiceCancelled field to the transaction schema  …
> MODINVOSTO-119 added Canceled status to the voucher schema

- mod-orders-storage/schemas/po_line.json
* https://issues.folio.org/browse/MODORDSTOR-237
* removed pattern from publicationDate field …
> MODORDSTOR-237 removed pattern from publicationDate field

- mod-orders-storage/schemas/po_line.json
- mod-orders/schemas/composite_po_line.json
> Modordstor 237

- mod-orders/schemas/checkinCollection.json
- mod-orders/schemas/receivingCollection.json
> [MODORDSTOR-235] - Add fields to checkinInColection

- mod-invoice-storage/schemas/invoice.json
> [MODINVOSTO-119] - Add cancellation note

- common/schemas/fund_code.json
- mod-finance/schemas/fund.json
- mod-orders-storage/schemas/fund_distribution.json
[MODORDSTOR-243](https://issues.folio.org/browse/MODORDSTOR-243)
Defined a new common schema for fund codes, used it for fund code and code in order fund distribution. …
> [MODORDSTOR-243] Restrict syntax for fund code in order fund distribution

- mod-orders-storage/examples/piece_collection.sample
- mod-orders-storage/examples/piece_get.sample
- mod-orders-storage/examples/piece_post.sample
- mod-orders-storage/examples/receiving_history_get.sample
- mod-orders-storage/schemas/piece.json
- mod-orders-storage/schemas/receiving_history.json
https://issues.folio.org/browse/MODORDSTOR-244
Update piece schema to include Copy number, update examples …
> MODORDSTOR-244 Update piece schema to include Copy number, *update examples

- mod-orders/schemas/checkinCollection.json
- mod-orders/schemas/receivingCollection.json
https://issues.folio.org/browse/MODORDSTOR-244
Updated checkinCollection and receivingCollection …
> MODORDSTOR-244 Update piece schema to include Copy number, Enumeration AND Chronology

- mod-finance/schemas/encumbrance_rollover.json
https://issues.folio.org/browse/MODFISTO-269
Updated encumbrance_rollover.json to be able to base encumbrance on "Initial encumbrance" during rollover …
> MODFISTO-269. Allow user to base encumbrance on "Initial encumbrance" during rollover

- mod-finance/schemas/encumbrance_rollover.json
https://issues.folio.org/browse/MODFISTO-269 …
> MODFISTO-269 Allow user to base encumbrance on "Initial encumbrance" during rollover

- mod-orders-storage/examples/acquisition_method_collection.sample
- mod-orders-storage/examples/acquisition_method_get.sample
- mod-orders-storage/examples/acquisition_method_post.sample
- mod-orders-storage/schemas/acquisition_method.json
- mod-orders-storage/schemas/acquisition_method_collection.json
Add acquisition method model
Create acquisition method model and samples
While it's …
> [MODORDSTOR-259] - Added acquisition method model

- mod-orders-storage/schemas/order_template.json
https://issues.folio.org/browse/MODORDSTOR-265 …
> MODORDSTOR-265. Orders Template should support hidden fields functionality

- mod-orders-storage/examples/acquisition_method_collection.sample
- mod-orders-storage/examples/acquisition_method_get.sample
- mod-orders-storage/examples/acquisition_method_post.sample
- mod-orders-storage/schemas/acquisition_method.json
Update acquisition method model
Add field 'source'
While it's helpful for reviewers to …
> [MODORDSTOR-259] - Updated acquisition method model

- mod-orders-storage/examples/po_line_collection.sample
- mod-orders-storage/examples/po_line_get.sample
- mod-orders-storage/examples/po_line_post.sample
- mod-orders-storage/schemas/po_line.json
- mod-orders/examples/composite_po_line.sample
- mod-orders/examples/composite_purchase_order.sample
- mod-orders/schemas/composite_po_line.json
Update schemes composite_po_line and po_lines …
> [MODORDSTOR-256] - Schemes updated

- mod-invoice-storage/examples/batch_voucher.sample
- mod-invoice-storage/schemas/batched_voucher.json
https://issues.folio.org/browse/MODINVOICE-262
Add two fields to batched voucher model. …
> MODINVOICE-262 - Include invoice date and terms in voucher export

- mod-orders-storage/examples/acquisition_method_collection.sample
- mod-orders-storage/schemas/acquisition_method_collection.json
https://issues.folio.org/browse/MODORDSTOR-267 …
> MODORDSTOR-267. Rename collection field name for Acquisition method collection

- mod-finance/examples/transaction.sample
- mod-finance/examples/transaction_collection.sample
- mod-finance/schemas/transaction.json
https://issues.folio.org/browse/MODFISTO-274 …
> MODFISTO-274. Extend transaction schema with voidedAmount field

- mod-finance/examples/transaction.sample
> MODFISTO-274. Update sample

- mod-orders/examples/composite_po_line.sample
- mod-orders/schemas/composite_po_line.json
> [MODORDSTOR] - Update comp line

- mod-orders-storage/examples/export_history.sample
- mod-orders-storage/examples/export_history_collection.sample
- mod-orders-storage/schemas/export_history.json
- mod-orders-storage/schemas/export_history_collection.json
> [MODORDSTOR-274] - Create export history schema

- mod-orgs/examples/organization_collection.sample
- mod-orgs/examples/organization_get.sample
- mod-orgs/examples/organization_post.sample
- mod-orgs/examples/organization_put.sample
- mod-orgs/examples/organization_type_collection.sample
- mod-orgs/examples/organization_type_get.sample
- mod-orgs/examples/organization_type_post.sample
- mod-orgs/schemas/organization.json
- mod-orgs/schemas/organization_type.json
- mod-orgs/schemas/organization_type_collection.json
[UXPROD-2553](https://issues.folio.org/browse/UXPROD-2553)
[MODORGSTOR-121](https://issues.folio.org/browse/MODORGSTOR-121) …
> [MODORGSTOR-121] - Add organization types

- mod-invoice-storage/schemas/batched_voucher.json
- mod-invoice-storage/schemas/batched_voucher_line.json
Add field "adjustments" in schema
While it's helpful for reviewers to help identify …
> [MODINVOICE-336] - Schema updated

- mod-invoice-storage/schemas/adjustment.json
Add field totalAmount
While it's helpful for reviewers to help identify potential …
> [MODINVOICE-336] - Added field totalAmount

- mod-orders-storage/schemas/ongoing.json
https://issues.folio.org/browse/MODORDSTOR-286
Set manualRenewal to false by default. …
> MODORDSTOR-286 - manual renewal set to false by default

- mod-orders/schemas/composite_purchase_order.json
[MODORDERS-636](https://issues.folio.org/browse/MODORDERS-636) - Update po lines when an order is closed with the "Cancelled" reason
Improved description for po closeReason, so we know this is not just free text.
Didn't add the whole list of system values because it would be hard to read in the generated doc, and we might change them in the future. …
> [MODORDERS-636] Improved description for po closeReason

- mod-orders-storage/schemas/po_line.json
*https://issues.folio.org/browse/MODEBSNET-30
* added renewal note field
While it's …
> MODEBSNET-30 added renewal note

- mod-finance/schemas/ledger_fiscal_year_rollover_error.json
https://issues.folio.org/browse/MODFIN-233
Adding "Other" ledger error type that will be used for any unexpected exceptions in rollover sql function. …
> MODFIN-233 - add Other rollover error type

- mod-orders/schemas/replace_order_line_instance_ref.json
[MODORDERS-684](https://issues.folio.org/browse/MODORDERS-684) …
> MODORDERS-684 Update replace_order_line_instance_ref

- mod-finance/schemas/ledger_fiscal_year_rollover_error.json
[MODFISTO-299](https://issues.folio.org/browse/MODFISTO-299) - Order and financial rollover errors are not reported
- Added 2 new error types
- Made details optional …
> [MODFISTO-299] Changed rollover error types, made details optional

- mod-orders-storage/schemas/vendor_detail.json
> [MODORDERS-697]-updated schema for vendor

- mod-orders/schemas/replace_order_line_instance_ref.json
https://issues.folio.org/browse/MODORDERS-716 …
> MODORDERS-716 Failing change instance connection from POL when Create inventory is "None"

- mod-orders/schemas/replace_order_line_instance_ref.json
> MODORDERS-716

- mod-gobi/schemas/OrderMappingsView.json
Fix missing description
While it's helpful for reviewers to help identify potential …
> [MODGOBI-160] - Updated acq-models

- mod-invoice/examples/validate_fund_distributions_request.sample
- mod-invoice/schemas/validate_fund_distributions_request.json
> [MODINVOICE-417]-Added schema

- mod-finance/examples/ledger_fiscal_year_rollover.sample
- mod-finance/examples/ledger_fiscal_year_rollover_budget.sample
- mod-finance/examples/ledger_fiscal_year_rollover_budget_collection.sample
- mod-finance/examples/ledger_fiscal_year_rollover_log.sample
- mod-finance/examples/ledger_fiscal_year_rollover_log_collection.sample
- mod-finance/schemas/ledger_fiscal_year_rollover.json
- mod-finance/schemas/ledger_fiscal_year_rollover_budget.json
- mod-finance/schemas/ledger_fiscal_year_rollover_budget_collection.json
- mod-finance/schemas/ledger_fiscal_year_rollover_log.json
- mod-finance/schemas/ledger_fiscal_year_rollover_log_collection.json
- mod-finance/schemas/ledger_rollover_type.json
Define schemas and table for storing generated Budgets and schema for showing rollover logs …
> Modfisto 319

- mod-finance/schemas/ledger_fiscal_year_rollover_budget.json
- mod-finance/schemas/ledger_fiscal_year_rollover_budget_collection.json
Correction of class names following the team's standards …
> [MODFISTO-319] Correction of class names

- mod-gobi/examples/orders_mapping.sample
https://issues.folio.org/browse/MODGOBI-157
* added order mappings example
While it's …
> MODGOBI-157 added order mappings example

- mod-gobi/examples/orders_mapping.sample
- mod-gobi/schemas/mapping.json
https://issues.folio.org/browse/MODGOBI-167 …
> [MODGOBI-167]-removed unused fields.

- mod-gobi/examples/orders_mapping.sample
- mod-gobi/schemas/mapping.json
> Modgobi 167

- mod-finance/examples/ledger_fiscal_year_rollover_log.sample
- mod-finance/examples/ledger_fiscal_year_rollover_log_collection.sample
- mod-finance/schemas/ledger_fiscal_year_rollover_log.json
- mod-finance/schemas/ledger_fiscal_year_rollover_log_collection.json
- mod-finance/schemas/ledger_rollover_type.json
- mod-finance/schemas/rollover_status.json
UI can construct links to budgets and errors using ledgerRolloverId.
- Remove unnecessary fields
[MODFIN-270](https://issues.folio.org/browse/MODFIN-270)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …
> [MODFIN-270] Define and implement Business API : Ledger Rollover Logs

- mod-orders-storage/examples/export_history.sample
- mod-orders-storage/schemas/export_history.json
https://issues.folio.org/browse/MODORDSTOR-315
> [MODORDSTOR-315]. Update schema for Export History

- mod-orders-storage/examples/export_history.sample
- mod-orders-storage/schemas/export_history.json
> [MODEXPW-273]-added field "jobName"

- mod-finance/schemas/encumbrance_rollover.json
- mod-finance/schemas/ledger_rollover_type.json
https://issues.folio.org/browse/MODORDERS-783
* fixed java naming …
> MODORDERS-783 fixed java naming

- mod-orders-storage/schemas/details.json
https://issues.folio.org/browse/MODORDSTOR-328
"isAcknowledged"-field needed inside mapping profile for Orders inside Details.
"isAcknowledged"-field added to the details.json …
> MODORDSTOR-328: Add isAcknowledged field for poLine details

- mod-invoice/examples/validate_fund_distributions_request.sample
- mod-invoice/schemas/validate_fund_distributions_request.json
> [MODORDSTOR-328] - ValidateFundDistributions model updated

- mod-finance/examples/transaction_encumbrance.sample
- mod-finance/schemas/transaction.json
[MODORDERS-834](https://issues.folio.org/browse/MODORDERS-834) …
> [MODORDERS-834] Mark invoice related encumbrances as deleted when changing fund distribution FLOW #2

- mod-finance/examples/transaction_encumbrance.sample
- mod-finance/schemas/transaction.json
Reverts folio-org/acq-models#414
> Revert "[MODORDERS-834] Mark invoice related encumbrances as deleted when changing fund distribution FLOW #2"

- mod-finance/examples/budget_rollover.sample
- mod-finance/examples/ledger_fiscal_year_rollover.sample
- mod-finance/examples/ledger_fiscal_year_rollover_collection.sample
- mod-finance/schemas/budget_rollover.json
To introduce new type of Rollover based on Cash balance
[MODFISTO-371](https://issues.folio.org/browse/MODFISTO-371) …
> [MODFISTO-371] - Add support to rollover cash balance during FY rollover

- mod-finance/examples/budget_rollover.sample
- mod-finance/examples/ledger_fiscal_year_rollover.sample
- mod-finance/examples/ledger_fiscal_year_rollover_collection.sample
- mod-finance/schemas/budget_rollover.json
In UI this field named as Rollover Budget Value, make name in schema consistent with UI
> [MODFISTO-371[ - Rename according UI field name

- mod-invoice-storage/examples/invoice.sample
- mod-invoice-storage/examples/invoice_collection.sample
- mod-invoice-storage/schemas/invoice.json
[MODINVOSTO-144](https://issues.folio.org/browse/MODINVOSTO-144) …
> [MODINVOSTO-144] - Added fiscalYearId field to Invoice DTO

- mod-orgs/examples/banking_account_type_collection.sample
- mod-orgs/examples/banking_account_type_get.sample
- mod-orgs/examples/banking_account_type_post.sample
- mod-orgs/schemas/banking_account_type.json
- mod-orgs/schemas/banking_account_type_collection.json
https://issues.folio.org/browse/MODORGSTOR-148
Create corresponding schemas
While it's …
> [MODORGSTOR-148] - BE - Implement CRUD for Banking Account Types

- mod-orgs/examples/organization_collection.sample
- mod-orgs/examples/organization_post.sample
- mod-orgs/schemas/organization.json
> [MODORG-59] - Introduce 'isDonor' indicator for organizations

- mod-orgs/examples/setting_collection.sample
- mod-orgs/examples/setting_get.sample
- mod-orgs/examples/setting_post.sample
- mod-orgs/schemas/setting.json
- mod-orgs/schemas/setting_collection.json
https://issues.folio.org/browse/MODORG-53
Create setting and collection of settings schemas. …
> [MODORG-53] - BE - Implement CRUD for Organization Settings

- mod-finance/examples/fund.sample
- mod-finance/schemas/fund.json
- mod-orders-storage/examples/piece_collection.sample
- mod-orders-storage/examples/piece_post.sample
- mod-orders-storage/examples/po_line_collection.sample
- mod-orders-storage/examples/po_line_get.sample
- mod-orders-storage/examples/po_line_post.sample
- mod-orders-storage/schemas/piece.json
- mod-orders-storage/schemas/po_line.json
- mod-orders/examples/composite_po_line.sample
- mod-orders/schemas/composite_po_line.json
> [MODORDERS-944/MODORDERS-948/MODFIN-333] BE - Added donor info to Fund and POL and receiving statuses for piece

- mod-finance/examples/fund_collection.sample
- mod-finance/examples/fund_details.sample
- mod-orgs/examples/banking_information_collection.sample
- mod-orgs/examples/banking_information_get.sample
- mod-orgs/examples/banking_information_post.sample
- mod-orgs/schemas/banking_information.json
- mod-orgs/schemas/banking_information_collection.json
[MODORG-54](https://issues.folio.org/browse/MODORG-54) - Banking information fields edit and delete …
> [MODORG-54] - Added bankingInformation

- mod-orgs/examples/organization_collection.sample
- mod-orgs/examples/organization_get.sample
- mod-orgs/examples/organization_post.sample
- mod-orgs/examples/organization_put.sample
- mod-orgs/schemas/organization.json
https://issues.folio.org/browse/MODORGSTOR-153
Add `privilegedContacts` field to existing schema and examples. …
> [MODORGSTOR-153] - BE - Implement API for Privileged contacts

- mod-orgs/schemas/banking_information.json
- mod-orgs/schemas/contact.json
- mod-orgs/schemas/organization_type.json
- mod-orgs/schemas/setting.json
Enable optimistic locking for table craeted in scope of https://issues.folio.org/browse/MODORGSTOR-153
Add "_version" field …
> [MODORGSTOR-153] - Allow optimistic locking

- mod-orgs/examples/banking_information_collection.sample
- mod-orgs/schemas/banking_information_collection.json
https://issues.folio.org/browse/MODORG-54
Changed name to `bankingInformationCollection` …
> [MODORG-54] - BE - Changing a number of banking information name

- mod-orgs/examples/banking_information_collection.sample
- mod-orgs/schemas/banking_information_collection.json
Reverts folio-org/acq-models#430
> Revert "[MODORG-54] - BE - Changing a number of banking information name"

- mod-finance/examples/fund.sample
- mod-finance/examples/fund_collection.sample
- mod-finance/examples/fund_details.sample
- mod-finance/schemas/fund.json
- mod-finance/schemas/fund_details.json
https://issues.folio.org/browse/MODFIN-337
added locationIds and missed donorOrganizationIds …
> [MODFIN-337] - Add locationIds to fund schema

- mod-orders-storage/examples/piece_collection.sample
- mod-orders-storage/examples/title_collection.sample
- mod-orders-storage/examples/title_get.sample
> [MODORDERS-954] - Added comma to missed places

- mod-orders-storage/examples/piece_audit_event.sample
- mod-orders-storage/examples/piece_get.sample
- mod-orders-storage/schemas/outbox_event_log.json
- mod-orders-storage/schemas/piece.json
- mod-orders-storage/schemas/piece_audit_event.json
https://issues.folio.org/browse/MODORDSTOR-357
Create/update corresponding types
While …
> [MODORDSTOR-357] - Implement the capability to send the modified state using a transactional outbox for Piece

- mod-orgs/examples/banking_information_collection.sample
- mod-orgs/examples/banking_information_get.sample
- mod-orgs/schemas/banking_information.json
Make field name consistent as in other places, use "isPrimary"
https://issues.folio.org/browse/MODORG-54
> MODORG-54. Update banking_information schema

- mod-orders-storage/schemas/piece.json
- mod-orders-storage/schemas/po_line.json
- mod-orders-storage/schemas/title.json
- mod-orders/schemas/composite_po_line.json
> [MODORDERS-945] - The default claimingInterval has been delete

- mod-finance/examples/fund.sample
- mod-finance/examples/fund_collection.sample
- mod-finance/examples/fund_details.sample
- mod-finance/schemas/fund.json
- mod-finance/schemas/fund_details.json
https://issues.folio.org/browse/MODFIN-342
> MODFIN-342. Add restictByLocations flag to Fund in acq models

- mod-orders-storage/examples/piece_audit_event.sample
- mod-orders-storage/examples/piece_collection.sample
- mod-orders-storage/examples/piece_get.sample
- mod-orders-storage/examples/piece_post.sample
- mod-orders-storage/schemas/piece.json
https://issues.folio.org/browse/MODORDERS-985
Added two fields - internalNote, externalNote - to piece schema …
> [MODORDERS-985] - Add internal note and external note in Piece schema

- mod-finance/examples/batch.sample
- mod-finance/schemas/batch.json
- mod-finance/schemas/transaction.json
[MODFIN-320](https://issues.folio.org/browse/MODFIN-320) - Create batch endpoint to update list of transactions at single request
Created the model that will be used in the new endpoint.
See also: [mod-finance-storage PR](https://github.com/folio-org/mod-finance-storage/pull/386), [mod-finance PR](https://github.com/folio-org/mod-finance/pull/223). …
> [MODFIN-320] New model for batch processing transactions

- mod-orders-storage/examples/piece_audit_event.sample
- mod-orders-storage/examples/piece_collection.sample
- mod-orders-storage/examples/piece_get.sample
- mod-orders-storage/examples/piece_post.sample
- mod-orders-storage/schemas/piece.json
https://issues.folio.org/browse/MODORDSTOR-369 …
> [MODORDSTOR-369] - Create migration script to change "caption" to "Display summary" for pieces

- mod-orders/examples/checkinCollection.sample
- mod-orders/schemas/checkinCollection.json
https://folio-org.atlassian.net/browse/MODORDERS-1022
> MODORDERS-1022. Add receiptDate to the schema

- mod-orders-storage/examples/piece_collection.sample
- mod-orders-storage/examples/piece_get.sample
- mod-orders-storage/schemas/piece.json
https://folio-org.atlassian.net/browse/MODORDSTOR-376
While it's helpful for reviewers …
> [MODORDSTOR-376] - Create "Bound" flag for receiving pieces

- mod-orders-storage/examples/piece_collection.sample
https://folio-org.atlassian.net/browse/MODORDSTOR-376
While it's helpful for reviewers …
> [MODORDSTOR-376] - Fix Syntax error : Missing ','

- mod-orders-storage/examples/po_line_collection.sample
- mod-orders-storage/examples/po_line_get.sample
- mod-orders-storage/schemas/location.json
- mod-orders-storage/schemas/po_line.json
- mod-orders/examples/composite_po_line.sample
https://folio-org.atlassian.net/browse/MODORDERS-1085
> MODORDERS-1085. Add ability to search by location and holding in POL

- mod-orders-storage/examples/order_line_audit_event.sample
- mod-orders/examples/composite_purchase_order.sample
- mod-orders/schemas/composite_po_line.json
https://folio-org.atlassian.net/browse/MODORDERS-1085
Update composite po line
> MODORDERS-1085. Add searchLocationIds array to composite po line

- mod-orders-storage/examples/title_collection.sample
- mod-orders-storage/examples/title_get.sample
- mod-orders-storage/examples/title_post.sample
- mod-orders-storage/schemas/title.json
https://folio-org.atlassian.net/browse/MODORDSTOR-393
Based on the association, we are adding bindItemIds to Title that will be used to all binding piece operating.
> Added bindItemIds to Title schema

- mod-orders-storage/examples/routing_list_collection.sample
- mod-orders-storage/examples/routing_list_get.sample
- mod-orders-storage/schemas/routing_list.json
Adding metadata to routing lists
> Add metadata to routing lists

- mod-orders/examples/bindPiecesCollection.sample
- mod-orders/schemas/bindPiecesCollection.json
> updated bindPiecesCollection.json

- mod-orders-storage/schemas/piece.json
https://folio-org.atlassian.net/browse/MODORDSTOR-376
Setting default false to avoid omit elements when query isBound=false because of not having value
> added default value for isBound flag

- mod-orders-storage/examples/piece_collection.sample
- mod-orders-storage/examples/piece_post.sample
- mod-orders-storage/schemas/piece.json
> MODORDSTOR-376 - isBound default values added to samples

- mod-orders/examples/bindPiecesCollection.sample
- mod-orders/schemas/bindPiecesCollection.json
[[MODORDERS-1122] Add logic to create item in any tenant for binding](https://folio-org.atlassian.net/browse/MODORDERS-1122)
* Add tenantId to BindItem schema
> MODORDERS-1122] Add logic to create item in any tenant for binding

- mod-orders/examples/bindPiecesCollection.sample
- mod-orders/examples/bindPiecesResult.sample
- mod-orders/schemas/bindPiecesCollection.json
- mod-orders/schemas/bindPiecesResult.json
- mod-orders/schemas/requestsAction.json
[[MODORDERS-1122] Add logic to create item in any tenant for binding](https://folio-org.atlassian.net/browse/MODORDERS-1122)
* Add bindPiecesResult as a return value for bind endpoint
> [MODORDERS-1122] Add logic to create item in any tenant for binding

- mod-orders/examples/bindPiecesCollection.sample
- mod-orders/schemas/bindPiecesCollection.json
Modify bind pieces endpoint to accept holdingId and locationId
* Add holdingId and locationId to bindPiecesCollection.json
> Modify bind pieces endpoint to accept holdingId and locationId

- mod-orders/examples/circulationRequestsCollection.sample
- mod-orders/schemas/circulationRequestsCollection.json
[[MODORDERS-1138] Implement endpoint to fetch Circulation requests for pieces](https://folio-org.atlassian.net/browse/MODORDERS-1138)
- Add new schema for response
> [MODORDERS-1138] Implement endpoint to fetch Circulation requests for pieces

- mod-orders-storage/schemas/piece.json
[[MODORDERS-1166] Add bindItemTenantId to Piece schema](https://folio-org.atlassian.net/browse/MODORDERS-1166)
- Add bindItemTenantId to Piece
> [MODORDERS-1166] Add bindItemTenantId to Piece schema

- mod-finance/examples/fund_update_log.sample
- mod-finance/examples/fund_update_log_collection.sample
- mod-finance/schemas/fund_update_log.json
- mod-finance/schemas/fund_update_log_collection.json
https://folio-org.atlassian.net/browse/MODFISTO-497
While it's helpful for reviewers to …
> [MODFISTO-497] - Create table and API for fund updates logs

- mod-invoice-storage/examples/invoice_audit_event.sample
- mod-invoice-storage/examples/invoice_line_audit_event.sample
- mod-invoice-storage/examples/outbox_event_log.sample
- mod-invoice-storage/schemas/event_action.json
- mod-invoice-storage/schemas/event_topic.json
- mod-invoice-storage/schemas/invoice.json
- mod-invoice-storage/schemas/invoice_audit_event.json
- mod-invoice-storage/schemas/invoice_line.json
- mod-invoice-storage/schemas/invoice_line_audit_event.json
- mod-invoice-storage/schemas/outbox_event_log.json
[[MODINVOSTO-187] Implement audit outbox pattern for sending kafka events about invoice updates](https://folio-org.atlassian.net/browse/MODINVOSTO-187)
- Add models for audit logs
> [MODINVOSTO-187] Implement audit outbox pattern for sending kafka events about invoice updates

- mod-finance/examples/fy_finance_data.sample
- mod-finance/examples/fy_finance_data_collection.sample
- mod-finance/schemas/fy_finance_data.json
- mod-finance/schemas/fy_finance_data_collection.json
https://folio-org.atlassian.net/browse/MODFISTO-500
- created object to handle finance data for fiscal year
> [MODFISTO-500] - Implement endpoint to return all finance data for FY

- mod-orgs/examples/organization_audit_event.sample
- mod-orgs/examples/outbox_event_log.sample
- mod-orgs/schemas/event_action.json
- mod-orgs/schemas/event_topic.json
- mod-orgs/schemas/organization.json
- mod-orgs/schemas/organization_audit_event.json
- mod-orgs/schemas/outbox_event_log.json
[[MODORGSTOR-164] Implement audit outbox pattern for sending kafka events about organization updates](https://folio-org.atlassian.net/browse/MODORGSTOR-164)
Add new models for kafka producer
> [MODORGSTOR-164] Implement audit outbox pattern for sending kafka events about organization updates

- mod-orders/examples/claimingCollection.sample
- mod-orders/examples/pieceStatusBatchCollection.sample
- mod-orders/schemas/claimingCollection.json
- mod-orders/schemas/pieceStatusBatchCollection.json
- <https://folio-org.atlassian.net/browse/MODORDERS-1209>
- Add 3 extra fields to Send Claims model
- Add 1 extra field to Piece Batch Update model
> [MODORDERS-1209-2]. Update Send Claims and Batch Piece Update models

- mod-orders/schemas/claimingCollection.json
- <https://folio-org.atlassian.net/browse/MODORDERS-1209>
- Fix extra field location on Send Claims model
> [MODORDERS-1209-3]. Fix Send Claims model

- mod-finance/examples/transaction_total_collection.sample
- mod-finance/schemas/transaction_total.json
- mod-finance/schemas/transaction_total_collection.json
- <https://folio-org.atlassian.net/browse/MODFIN-391>
- Create additional models for transaction totals aggregation in SQL
> [MODFIN-391]. Minimize amount of requests to retrieve transactions for ledger

- mod-finance/schemas/fy_finance_data.json
https://folio-org.atlassian.net/browse/MODFIN-388
- Removed default value
> [MODFIN-388] - remove default value

- mod-finance/examples/fy_finance_data_collection_get.sample
- mod-finance/schemas/fy_finance_data.json
https://folio-org.atlassian.net/browse/MODFIN-403
- adding isChanged fields to finance data …
> [MODFIN-403] - add isChanged field to finance-data

- mod-finance/examples/fy_finance_data_collection_put.sample
- mod-finance/schemas/fy_finance_data.json
- mod-finance/schemas/fy_finance_data_collection.json
https://folio-org.atlassian.net/browse/MODFIN-415
While it's helpful for reviewers to …
> [MODFIN - 415] - Batch allocation bugs/enhancements 

- mod-finance/schemas/budget.json
- mod-finance/schemas/shared_budget.json
[MODFIN-405](https://folio-org.atlassian.net/browse/MODFIN-405) - Current budget is created with incorrect values ​​despite the received error
Added a constraint to `allowableEncumbrance` and `allowableExpenditure` for mod-finance and mod-finance-storage budgets, so budgets are not created or updated with a negative percentage.
Another PR will be created in mod-finance after this ticket is merged.
- Are the JIRAs under active …
> Minimum of 0 for allowable encumbrance and expenditure

- mod-orders-storage/examples/order_template_category_collection.sample
- mod-orders-storage/examples/order_template_category_get.sample
- mod-orders-storage/examples/order_template_category_post.sample
- mod-orders-storage/examples/order_template_get.sample
- mod-orders-storage/schemas/order_template.json
- mod-orders-storage/schemas/order_template_category.json
- mod-orders-storage/schemas/order_template_category_collection.json
- mod-orders-storage/schemas/order_template_collection.json
https://folio-org.atlassian.net/browse/MODORDSTOR-443
While it's helpful for reviewers …
> [MODORDERSTOR - 443] - Implement API for Order Template Categories

- mod-mosaic/examples/mosaic_order.sample
- mod-mosaic/examples/mosaic_order_request.sample
- mod-mosaic/schemas/mosaic_order.json
- mod-mosaic/schemas/mosaic_order_request.json
https://folio-org.atlassian.net/browse/MODMO-10 …
> [MODMO-10] - Implement initial version of mapper from mod-mosaic order to Folio order

- mod-orders-storage/examples/order_template_get.sample
- mod-orders-storage/schemas/order_template.json
https://folio-org.atlassian.net/browse/MODORDSTOR-443
Order template can be assigned to multiple categories
> MODORDSTOR-443-2. Update order template schema

- mod-mosaic/examples/mosaic_order.sample
- mod-mosaic/examples/mosaic_order_request.sample
- mod-mosaic/schemas/mosaic_order.json
https://folio-org.atlassian.net/browse/MODMO-11
- add required fields and improve dto …
> [MODMO-11] - Implemnet logic to create order based on Order Template

- mod-mosaic/examples/mosaic_order.sample
- <https://folio-org.atlassian.net/browse/EDGORDERS-96>
- Update mosaic create order sample to aid the utilization of the POST /mosaic/orders API in edge-orders
> [EDGORDERS-96]. Update mosaic create order sample

- mod-mosaic/schemas/mosaic_order.json
Use the same enum to simplify contract
> Simplify contract to make the same as in Purchase order

- mod-mosaic/examples/mosaic_order.sample
- mod-mosaic/examples/mosaic_order_request.sample
- mod-mosaic/schemas/mosaic_order.json
- <https://folio-org.atlassian.net/browse/MODMO-14>
- Add WorkflowStatus field to MosaicOrder schema
- Update examples
> [MODMO-14]. Cover mosaic integrations with Karate tests

- mod-invoice-storage/examples/adjustment_preset.sample
- mod-invoice-storage/examples/adjustment_preset_collection.sample
- mod-invoice-storage/schemas/adjustment_preset.json
- mod-invoice-storage/schemas/adjustment_preset_collection.json
[[MODINVOSTO-202] Create Api for storing Invoice adjustments](https://folio-org.atlassian.net/browse/MODINVOSTO-202)
- Add new schemas for adjustment presets
---
> [MODINVOSTO-202] Create Api for storing Invoice adjustments
