folio-org/acq-models

mod-orders/schemas/composite_purchase_order.json
Since we moved mod-orders to mod-orders-storage, the composite_purchase_order.json file I was using locally against the old mod-orders needed its refs updated to point to mod-orders-storage and it was missed... Oops!
=> Forgot to update the composite PO schema

mod-orders-storage/schemas/adjustment_collection.json, mod-orders-storage/schemas/alert_collection.json, mod-orders-storage/schemas/claim.json, mod-orders-storage/schemas/claim_collection.json, mod-orders-storage/schemas/cost_collection.json, mod-orders-storage/schemas/details_collection.json, mod-orders-storage/schemas/eresource_collection.json, mod-orders-storage/schemas/license_collection.json, mod-orders-storage/schemas/location_collection.json, mod-orders-storage/schemas/physical_collection.json, mod-orders-storage/schemas/po_line_collection.json, mod-orders-storage/schemas/purchase_order_collection.json, mod-orders-storage/schemas/renewal_collection.json, mod-orders-storage/schemas/reporting_code_collection.json, mod-orders-storage/schemas/source_collection.json, mod-orders-storage/schemas/vendor_detail_collection.json
Add description fields to mod-orders-storage *collection schemas, as well as one top-level description that was missed earlier (claim.json).
See [MODORDSTOR-12](https://issues.folio.org/browse/MODORDSTOR-12) for details.
I think this addresses the last of the orders-related raml-cop issues!!!
```
mod-orders$ python3 ../folio-tools/lint-raml/lint_raml_cop.py -l info
INFO: lint-raml-cop: Investigating mod-orders/ramls
INFO: lint-raml-cop: Using submodule ramls/raml-util at 45d45e8cdac093d854673a791a1d73fe0f1e18e9
INFO: lint-raml-cop: Looking for schema files: ./ramls/acq-models/mod-orders-storage/schemas
INFO: lint-raml-cop: Assessing schema files:
INFO: lint-raml-cop: reporting_code_collection.json: Each property "description" is present.
INFO: lint-raml-cop: license_collection.json: Each …
```
=> MODORDSTOR-12 - Add description fields to mod-orders-storage collection schemas

composite_purchase_order.json, examples/composite_purchase_order.sample, examples/composite_purchase_orders.sample, mod-orders-storage/examples/purchase_order_collection.sample, mod-orders-storage/examples/purchase_order_get.sample, mod-orders-storage/examples/purchase_order_post.sample, mod-orders-storage/schemas/close_reason.json, mod-orders-storage/schemas/purchase_order.json
Defined `close_reason.json` schema. Updated PO and composite PO schemes and samples.
No separate tables were created, so close_reason object completely stores in `purchase_order` table as part of PO.
=> Modorders 92 - Added Close Reason of PO schema

mod-orders-storage/schemas/po_number.json
*PURPOSE*
Fixing https://issues.folio.org/browse/MODORDSTOR-33
*APPROACH*
PO Number should be a 5-16 AplphaNumeric Characters
=> Fixing MODORDSOTR-33: PO Number must be alphaNumeric

NEWS.md, composite_purchase_order.json, examples/composite_purchase_order.sample, examples/composite_purchase_orders.sample, mod-orders-storage/examples/purchase_order_collection.sample, mod-orders-storage/examples/purchase_order_get.sample, mod-orders-storage/examples/purchase_order_post.sample, mod-orders-storage/schemas/po_number.json, mod-orders-storage/schemas/purchase_order.json
User must have the ability to add prefix or suffix to PO number when creating a purchase order. This allows the user to add the desired context to the PO number without needing to edit the sequential number that the system has generated. Please refer to [MODORDERS-96](https://issues.folio.org/browse/MODORDERS-96) for more details.
- Adding `poNumberPrefix` and `poNumberSuffix` to the purchase_order/po_number/composite_purchase_order schemas.
- The po_number.json schema updated as well so it can be used for validation of the combination prefix + po_number + suffix (please see [MODORDERS-89](https://issues.folio.org/browse/MODORDERS-89)) because only business logic module should be aware about the approach of how to concatenate these data
- Updating examples
=> MODORDERS-108 Define po_number prefix and suffix

composite_po_line.json, mod-orders-storage/schemas/po_line.json
According to the latest requirements, the list of allowed values for "order_format" field should be as follows:
- Electronic Resource
- Physical Resource
- P/E Mix
- Other
- composite_po_line.json and po_line.json schemas were updated
- the samples are not updated as they are already in agreement with the latest list
- once this PR is merged, mod-orders and mod-orders-storage modules must be updated to point the latest version of acq-models sub-module
=> MODORDSTOR-40 Unable to save Line with order_format Other

composite_purchase_order.json
[MODORDERS-128](https://issues.folio.org/browse/MODORDERS-128)  In case a request that contains an empty po_lines array, all the PO Lines should be removed
- changed default value of po_lines from empty list to null, so that we can distinguish when the request does not include po_lines and when it contains empty array of poLines.
=> MODORDERS-128 PUT orders - handle empty array of the PO lines

composite_po_line.json, composite_purchase_order.json, mod-orders-storage/schemas/po_line.json
make "source" a required element
set default value for workflow_status
* PO line "source" element must be required according to the documentation
* PO "workflow_status" must be required according to the documentation
https://docs.google.com/spreadsheets/d/1F88PoSnEKD7oFnza1ZuOgzAgKnK95XOyTQzxyww3tZA/edit#gid=1408113181&range=A92
* Update po_line.json (storage schema) and composite_po_line.json (mod-orders schema) to make "source" element required, so that it is enforced by the validation logic
* Update composite_purchase_order.json schema to specify default value of "Pending" for workflow_status
This is alternative (and likely better) option to simply making it mandatory and requiring clients to always provide one.
=> MODORDERS-145 Unable to create new Purchase Order with PO Line

composite_purchase_order.json, examples/composite_purchase_order.sample, examples/composite_purchase_orders.sample, mod-orders-storage/examples/purchase_order_get.sample, mod-orders-storage/schemas/purchase_order.json
[MODORDERS-147](https://issues.folio.org/browse/MODORDERS-147) Update Purchase Order schema: Add dateOrdered field
- added dateOrdered to purchase_order and composite_purchase_order schemas
- set "readOnly": true for "dateOrdered" field in composite_purchase_order schema
- samples updated
=> MODORDERS-147 Update Purchase Order schema: Add dateOrdered field

mod-orders-storage/schemas/purchase_order.json
[MODORDERS-150](https://issues.folio.org/browse/MODORDERS-150) Define default workflow status
Defining `Pending` status as default value for workflow status in the purchase order schema
=> MODORDERS-150 Saving Order with modified po_number field fails

mod-vendors/examples/vendor_get.sample, mod-vendors/examples/vendor_post.sample, mod-vendors/examples/vendor_put.sample, mod-vendors/schemas/vendor.json
The vendor creation form requires a way to specify the expected receipt interval for a given vendor.  Behaviour conforms to the restrictions of an integer.
https://issues.folio.org/browse/MODVEND-75
The property was added to the vendor model as an integer.
=> MODVEND-75 Added expected_receipt_interval property to mod-vendor.vendor.json model

composite_po_line.json, examples/composite_po_line.sample, examples/composite_purchase_order.sample, mod-orders-storage/examples/po_line_collection.sample, mod-orders-storage/examples/po_line_get.sample, mod-orders-storage/examples/po_line_post.sample, mod-orders-storage/schemas/po_line.json
[MODORDERS-154](https://issues.folio.org/browse/MODORDERS-154) PO Line: make location details repeatable
* Replace single location by array of location objects in composite PO Line schema
* Replace single location uuid by array of location uuid's in PO Line schema
* Update samples
The PR can be merged only once changes are ready for following repositories
=> MODORDERS-154 make location repeatable

composite_po_line.json
[MODORDERS-93](https://issues.folio.org/browse/MODORDERS-93)
The goal is to disable the ability to set a value for "po_line_number" using put and post requests
- made "po_line_number" field readonly for compositePoLine
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
=> MODORDERS-93 po_line_number isn't set when creating a new po_line

mod-orders/examples/receivingCollection.sample, mod-orders/examples/receivingResults.sample, mod-orders/schemas/receivingCollection.json, mod-orders/schemas/receivingResults.json
[MODORDERS-103](https://issues.folio.org/browse/MODORDERS-103) Implement receiving flow for physical resources
Please see [Update Item Details sketch](https://sketch.cloud/s/RMywj/4ax51jq/play). User can specify desired item status. Receiving API should accept the status.
Adding desired items status to the receiving collection
=> MODORDERS-103 Implement receiving flow for physical resource

composite_po_line.json, mod-orders-storage/schemas/po_line.json
According to [MODORDERS-159](https://issues.folio.org/browse/MODORDERS-159)
If the order is in pending state, if not specified, the receipt status should default to "Pending"
* adding default PO line receipt_status to `po_line` and `composite_po_line` schemas …
=> MODORDERS-159 added default poline receipt_status

mod-orders-storage/examples/receiving_history_collection.sample, mod-orders-storage/examples/receiving_history_get.sample, mod-orders-storage/schemas/receiving_history.json
[MODORDSTOR-61](https://issues.folio.org/browse/MODORDSTOR-61) add ability to differentiate pieces for receiving and check-in flows. The piece record might refer to Inventory instance but without created inventory item. 
- added checkinItems and instanceId properties to receiving_history schema
- samples updated
Ideally all of the PRs involved in …
=> MODORDSTOR-61 Receiving history: updates to support check-in flow

mod-orders/schemas/composite_po_line.json
The missing mod-orders-storage reference fails to generate the correct POJOs
Fix the missing mod-orders-storage reference of contributors object  …
=> MODORDERS-158- Typo Fix

mod-orders-storage/schemas/po_line.json, mod-orders/examples/composite_purchase_orders.sample, mod-orders/schemas/composite_po_line.json
[MODORDSTOR-70](https://issues.folio.org/browse/MODORDSTOR-70) - Make poLine.checkinItems default to false
The poLine and compositePoLine schemas should be updated to use a default of false to avoid confusion when poLine.checkinItems field is omitted and won't appear in the receiving history for that poLine.
po_line.json/composite_po_line.json schemas updating -> checkinItems: default value setted to false
=> MODORDSTOR-70 - Make poLine.checkinItems default to false

mod-invoice-storage/examples/invoice_line.sample, mod-invoice-storage/schemas/invoice_line.json
[MODINVOSTO-4](https://issues.folio.org/browse/MODINVOSTO-4) - Implement Basic CRUD APIs for invoice-lines
According to story requirements one need to allow save "invoiceLineNumber" in the storage. This means one need to make this field not only for reading.
Note: additionally updated example for invoice_line.sample - as per schema "quantity" field should be integer.
Remove modifier "readOnly": true for "invoiceLineNumber" field in the invoice_line.json schema
**"mod-invoice-storage", "mod-invoice"**
=> MODINVOSTO-4 - Implement Basic CRUD APIs for invoice-lines

mod-orders-storage/schemas/po_line.json, mod-orders/schemas/composite_po_line.json
[MODORDERS-211](https://issues.folio.org/browse/MODORDERS-211) POL paymentStatus should be updated when opening an order.
made paymentStatus default "Pending"
=> MODORDERS-211 Align POL Payment and Receipt status with PO Status when opening order

mod-orgs/schemas/organization.json
[MODORGS-25] Make organization.status an enum
- made organization.status an enum
While …
=> MODORGS-25 Make organization.status an enum

mod-orgs/schemas/address.json
https://issues.folio.org/browse/MODORGS-26
* making address country field not required
Also was found that `addressLine1` field is required according to [Acquisitions Interface Fields](https://docs.google.com/spreadsheets/d/1F88PoSnEKD7oFnza1ZuOgzAgKnK95XOyTQzxyww3tZA/edit#gid=2127691361&range=C13), but currently this field is not required.
Ideally all …
=> MODORGS-26 Country should not be a required field

mod-finance/schemas/encumbrance.json
[MODORDERS-243](https://issues.folio.org/browse/MODORDERS-243) Create encumbrance upon order transition to "Open"
Making `budgetId` optional - the orders app has only fund distribution which has only fundId
=> MODORDERS-243 Make budget id in encumbrance optional

common/schemas/product_id_type.json, mod-invoice-storage/examples/invoice_line.sample, mod-invoice-storage/examples/invoice_line_collection.sample, mod-orders-storage/examples/po_line_collection.sample, mod-orders-storage/examples/po_line_get.sample, mod-orders-storage/examples/po_line_post.sample, mod-orders/examples/composite_po_line.sample, mod-orders/examples/composite_purchase_order.sample
https://issues.folio.org/browse/MODORDERS-252
There are 2 ways to do this:
1. Update this schema as done in this PR
2. Delete product_id_type.json completely and update each schema where it is used
Currently, `product_id_type.json` is used in 2 places `mod-orders-storage/schemas/details.json` and `mod-invoice-storage/schemas/invoice_line.json` So, I will go ahead with option 1 so that will keep our options open in case other modules decide to use `product_type_id` in future. Other modules can just ref it.
- Update examples
Note - This PR will not be merged until mod-order-storage and mod-orders are ready.
- Does this introduce breaking …
=> MODORDERS-252: Make productIdType to be uuid (acq-model)

mod-invoice-storage/examples/invoice.sample, mod-invoice-storage/examples/invoice_collection.sample, mod-invoice-storage/schemas/invoice.json
[MODINVOSTO-24](https://issues.folio.org/browse/MODINVOSTO-24) add billTo and exportToAccounting properties
Adding 2 new properties to invoice.json schema
=> MODINVOSTO-24 add billTo and exportToAccounting properties

mod-orders-storage/schemas/claim.json, mod-orders-storage/schemas/eresource.json, mod-orders-storage/schemas/po_line.json, mod-orders-storage/schemas/purchase_order.json, mod-orders-storage/schemas/renewal.json
[MODORDSTOR-98](https://issues.folio.org/browse/MODORDSTOR-98) filterable `boolean` properties should have default value
Adding default value for `boolean` properties which have Y in "Filter on this?" column in [Acquisitions Interface Fields - Orders](https://docs.google.com/spreadsheets/d/1F88PoSnEKD7oFnza1ZuOgzAgKnK95XOyTQzxyww3tZA/edit#gid=1408113181)
=> MODORDSTOR-98 filterable boolean properties to have default value

mod-orders-storage/examples/acquisitions_unit_membership_post.sample
[MODORDERS-250](https://issues.folio.org/browse/MODORDERS-250) - Implement basic CRUD for /acquisitions-units/memberships
Adding sample for POST acquisitions unit membership.
Adding sample for POST acquisitions_unit_membership_post.sample.
=> MODORDERS-250 - Implement basic CRUD for /acquisitions-units/memberships

common/schemas/uuid.json, mod-orders-storage/examples/purchase_order_collection.sample, mod-orders-storage/examples/purchase_order_get.sample, mod-orders-storage/examples/purchase_order_post.sample, mod-orders-storage/schemas/purchase_order.json, mod-orders/examples/composite_purchase_order.sample, mod-orders/examples/composite_purchase_orders.sample, mod-orders/schemas/composite_purchase_order.json
[MODORDERS-251](https://issues.folio.org/browse/MODORDERS-251) - Restrict creation of PO, POL, Piece records based upon acquisitions unit.
In scope of [MODORDERS-251](https://issues.folio.org/browse/MODORDERS-251) one need to implement support of unit IDs array on composite po and purchase order schemes to  restrict managing of purchase order based on acquisition units.
UUID type picked out to separate file uuid.json;
composite po schema contains array of IDs:
```
"units": {
"description": "unit ids associated with this purchase order",
"id": "units",
"type": "array",
"items": {
"$ref": "../../common/schemas/uuid.json"
}
}
```
- Does this …
=> MODORDERS-251 - Restrict creation of PO, POL, Piece records based upon acquisitions unit

mod-invoice-storage/examples/invoice.sample, mod-invoice-storage/examples/invoice_collection.sample, mod-invoice-storage/examples/voucher.sample, mod-invoice-storage/examples/voucher_collection.sample, mod-invoice-storage/schemas/invoice.json, mod-invoice-storage/schemas/voucher.json, mod-orders-storage/schemas/purchase_order.json, mod-orders/schemas/composite_purchase_order.json
[MODINVSTO-28](https://issues.folio.org/browse/MODINVOSTO-28)
[MODINVSTO-31](https://issues.folio.org/browse/MODINVOSTO-31)
According to [option 3](https://wiki.folio.org/display/FOLIJET/Acquisition+Units#AcquisitionUnits-OrderofOperations/Chicken&EggProblem), acquisitions-unit-assignments should become part of the invoice and voucher schemes.
Ideally …
=> MODINVOSTO-28/MODINVOSTO-31 Add acqUnitIds to Invoice and Voucher schemes

acquisitions-unit/examples/acquisitions_unit_collection.sample, acquisitions-unit/examples/acquisitions_unit_get.sample, acquisitions-unit/examples/acquisitions_unit_post.sample, acquisitions-unit/schemas/acquisitions_unit.json
[MODORDERS-293](https://issues.folio.org/browse/MODORDERS-293) Acquisition units - soft delete
Adding a `isDeleted` field to the acquisition_units schema - boolean, default: false, required.
=> MODORDERS-293 Acquisition units - soft delete

mod-orders-storage/examples/po_line_collection.sample, mod-orders-storage/examples/po_line_get.sample, mod-orders-storage/examples/po_line_post.sample, mod-orders-storage/schemas/fund_distribution.json, mod-orders/examples/composite_po_line.sample, mod-orders/examples/composite_purchase_order.sample
[MODORDSTOR-109](https://issues.folio.org/browse/MODORDSTOR-109) Allow fund distributions to be specified as amount or percentage
Updating schema and samples
=> MODORDSTOR-109 Allow fund distributions to be specified as amount or percentage

mod-finance/examples/composite_fund.sample, mod-finance/schemas/composite_fund.json
[MODFIN-76](https://issues.folio.org/browse/MODFIN-76) - CompositeFund schema
In order to keep the UI logic simple, we're introducing a new schema used between the business logic module and the UI: composite_fund with groupIds array<string> field.
composite_fund.json schema added,
example added.
=> MODFIN-76 - CompositeFund schema

mod-orders/examples/checkinCollection.sample, mod-orders/examples/receivingCollection.sample, mod-orders/schemas/checkinCollection.json, mod-orders/schemas/receivingCollection.json
https://issues.folio.org/browse/MODORDERS-315
- Update checkinCollection and receivingCollection schema to make `itemStatus` optional
- Need to make it optional so when `itemStatus` is empty, it will default to "In process" during 
receiving/checkin
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> MODORDER-315: Default to "In process" for item status during receiving/check-in

mod-orders/examples/checkinCollection.sample, mod-orders/examples/receivingCollection.sample, mod-orders/schemas/checkinCollection.json, mod-orders/schemas/item_status.json, mod-orders/schemas/receivingCollection.json
[MODORDERS-353](https://issues.folio.org/browse/MODORDERS-353) - Migrate to new major version of item-storage, inventory, circulation
Making of enumeration of orders-specific item statuses in the schema.
Item statuses enumeration of order-specific statuses. …
=> MODORDERS-353 - Migrate to new major version of item-storage, inventory, circulation

mod-orgs/schemas/organization.json
[MODORGS-53](https://issues.folio.org/browse/MODORGS-53) - Organization code optional in back-end, required in front-end
In the front-end the organization code is required, but non-required in back-end.
Organization schema changing - code becomes required. …
=> MODORGS-53 - Organization code optional in back-end, required in front-end

mod-invoice-storage/examples/credentials.sample, mod-invoice-storage/schemas/credentials.json
I've decided to go a slightly different route than what's on the wiki page wrt batch voucher export configuration credentials in that these records should have their own `id` as well as an explicit reference to the export configuration they're associated with (`exportConfigId`).  This is consistent with how we manage interface credentials in organizations-storage.  I also discussed this with the tech leads and the preference is to have distinct ids in these situations.
* Add `exportConfigId` and make required
* Make `id` optional and fix it's description
* Update schema example
If there are breaking …
=> MODINVOSTO-52 - Distinct id/exportConfigId fields

mod-orgs/examples/organization_collection.sample, mod-orgs/examples/organization_get.sample, mod-orgs/examples/organization_post.sample, mod-orgs/examples/organization_put.sample, mod-orgs/schemas/account.json, mod-orgs/schemas/organization.json
[MODORGSTOR-67](https://issues.folio.org/browse/MODORGSTOR-67) - Add an "acqUnitIds" field to the organization schema
To enable support of acquisition units for organizations management
Adding non-mandatory array of acq unit IDs in the organization schema …
=> MODORGSTOR-67 - Add an "acqUnitIds" field to the organization schema

mod-orders-storage/examples/piece_collection.sample, mod-orders-storage/examples/piece_get.sample, mod-orders-storage/examples/piece_post.sample, mod-orders-storage/schemas/piece.json
[MODORDSTOR-135](https://issues.folio.org/browse/MODORDSTOR-135)
In order to support filtering titles by information in the associated piece record, we need to add a titleId field to the piece schema and create a foreign key.
- Add titleId into the pieces …
=> [MODORDSTOR-135] Add titleId field to the piece schema and create a foreign key

common/schemas/entity.json, mod-orders-storage/schemas/prefix.json, mod-orders-storage/schemas/purchase_order.json, mod-orders-storage/schemas/reason_for_closure.json, mod-orders-storage/schemas/suffix.json
[MODORDERS-389](https://issues.folio.org/browse/MODORDERS-389) to have a basic class for models in order to simplify the development of generic functionality.
- adding base entity.json schema for records with id
- config, purchase_order schemas extend entity.json …
=> MODORDERS-389 Unable to remove prefixes/suffixes that are currently used by an existing orders

mod-orders-storage/examples/po_line_collection.sample, mod-orders-storage/examples/po_line_get.sample, mod-orders-storage/schemas/eresource.json
[MODORDSTOR-147](https://issues.folio.org/browse/MODORDSTOR-147) - Add resourceUrl field to the eresource schema
In order to support UIOR-556, we need to update the eresource.json schema.
* Added optional "resourceUrl" field to the ramls/acq-models/mod-orders-storage/schemas/eresource.json.
* Updated samples
Ideally all of the PRs involved in breaking …
=> MODORDSTOR-147 - Add resourceUrl field to the eresource schema

Jenkinsfile, README.md
The old buildNode is deprecated.
In Jenkinsfile, use the new buildNode label "jenkins-agent-java11" instead of the old label "jenkins-slave-all".
See [FOLIO-2926](https://issues.folio.org/browse/FOLIO-2926)
=> MODFISTO-207 FOLIO-2926 Use buildNode jenkins-agent-java11

Jenkinsfile
Ensure that API JSON Schema has property descriptions.
Replaces old RAML facility.
See [FOLIO-2917](https://issues.folio.org/browse/FOLIO-2917).
=> FOLIO-2917 Use api-schema-lint facility

mod-finance/schemas/expense_class.json, mod-finance/schemas/fund.json
[MODFISTO-244](https://issues.folio.org/browse/MODFISTO-244) - Add validation for special character to Fund Code and Expense class code and prepare migration script
- Fund codes and expense class codes can no longer use the character ":" (colon)
- Expense class code is now a required field
Ideally all of the PRs involved in breaking changes would be …
=> [MODFISTO-244] Restrict code syntax, expense class code required

mod-orders-storage/examples/po_line_get.sample, mod-orders-storage/schemas/po_line.json
https://issues.folio.org/browse/MODORDSTOR-277 …
=> [MODORDSTOR-277] - Add field "lastEDIExportDate" into POL to support filtering on UI side

mod-finance/schemas/budget.json, mod-finance/schemas/budget_expense_class.json, mod-finance/schemas/expense_class.json, mod-finance/schemas/fiscal_year.json, mod-finance/schemas/fund.json, mod-finance/schemas/fund_type.json, mod-finance/schemas/group.json, mod-finance/schemas/group_fund_fiscal_year.json, mod-finance/schemas/ledger.json, mod-finance/schemas/ledger_fiscal_year_rollover.json, mod-finance/schemas/shared_budget.json, mod-finance/schemas/transaction.json
[MODFISTO-303](https://issues.folio.org/browse/MODFISTO-303) - Enable optimistic locking (for finance)
Added a _version attribute to the relevant schemas.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …
=> [MODFISTO-303] Added a _version field to some finance schemas

mod-finance/schemas/ledger_fiscal_year_rollover_budget.json
In recently schema changes was added field with name "withOptimisticLocking" to new table "ledger_fiscal_year_rollover_budget":
We should add _version field for successfully serialization/deserialization pojo
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …
=> [MODFISTO-319] Added missed optimistic locking field

mod-orders-storage/examples/order_audit_event.sample, mod-orders-storage/examples/order_line_audit_event.sample, mod-orders-storage/schemas/event_action.json, mod-orders-storage/schemas/order_audit_event.json, mod-orders-storage/schemas/order_line_audit_event.json, mod-orders-storage/schemas/po_line.json, mod-orders-storage/schemas/purchase_order.json
https://issues.folio.org/browse/MODORDSTOR-324
Add schemas for audit event logs . These schemas will be copied to mod-audit repo, but instead of entities PurchaseOrder and PoLine string objects will be used
=> MODORDSTOR-324. Add audit log message schemas

mod-orders-storage/examples/purchase_order_get.sample, mod-orders-storage/schemas/purchase_order.json, mod-orders/examples/composite_purchase_order.sample, mod-orders/schemas/composite_purchase_order.json
[MODORDERS-494](https://issues.folio.org/browse/MODORDERS-494) - Unexpected jump in POL number on 2 line PO
Added a new field to orders and composite orders: `nextPolNumber`.
This is needed for a future PR in mod-orders-storage. Also mod-orders and mod-invoice will need updated models.
Ideally all of the PRs involved in breaking changes would be merged …
=> [MODORDERS-494] New order field: nextPolNumber

mod-invoice-storage/examples/export_configuration.sample, mod-invoice-storage/schemas/export_configuration.json
We need to support sftp login.
Currently Settings UI to upload batch groupls looks like this:
Correct SFTP URI string looks like this:
"sftp://" + username + ":" + password + "@" + remoteHost + "/" + remoteDir + "file.txt");
Because we already have username and password as separate fields and need to intoduce new field for chosing ftp/sfpt - so uploadURI should contain only host. For ftp port introduced new field to have the same user experience as for EDI export.
Also added uplodDirectory for future if user wants to save exports in different folder, default is: /files/invoices
=> MODINVOICE-455. Update models schema with new fields for ftp configuration

mod-orders-storage/examples/order_line_audit_event.sample, mod-orders-storage/examples/piece_collection.sample, mod-orders-storage/examples/piece_get.sample, mod-orders-storage/examples/piece_post.sample, mod-orders-storage/examples/po_line_collection.sample, mod-orders-storage/examples/po_line_get.sample, mod-orders-storage/examples/po_line_post.sample, mod-orders-storage/examples/title_collection.sample, mod-orders-storage/examples/title_get.sample, mod-orders-storage/examples/title_post.sample, mod-orders-storage/schemas/piece.json, mod-orders-storage/schemas/po_line.json, mod-orders-storage/schemas/title.json, mod-orders/examples/composite_po_line.sample, mod-orders/examples/composite_purchase_order.sample, mod-orders/schemas/composite_po_line.json
…ted models
While it's helpful for reviewers to help identify potential problems, …
=> [MODORDERS-945, MODORDERS-953, MODORDERS-954] - Updated claiming related acq-models

acquisitions-unit/examples/acquisitions_unit_get.sample, acquisitions-unit/examples/acquisitions_unit_post.sample, acquisitions-unit/schemas/acquisitions_unit.json, mod-orgs/examples/banking_information_collection.sample, mod-orgs/examples/banking_information_get.sample, mod-orgs/examples/banking_information_post.sample, mod-orgs/schemas/banking_information.json
https://issues.folio.org/browse/MODORDERS-966
Add the corresponding field.
While it's …
=> [MODORDERS-966] - Add description to acq unit dto schema

mod-orders-storage/examples/po_line_collection.sample, mod-orders-storage/examples/po_line_get.sample, mod-orders-storage/examples/purchase_order_collection.sample, mod-orders-storage/examples/purchase_order_get.sample, mod-orders-storage/schemas/po_line.json, mod-orders-storage/schemas/purchase_order.json, mod-orders/examples/composite_po_line.sample, mod-orders/examples/composite_purchase_order.sample, mod-orders/schemas/composite_po_line.json, mod-orders/schemas/composite_purchase_order.json
Integration of custom fields into orders modules. See [MODORDERS-964](https://issues.folio.org/browse/MODORDERS-964).
Attribute `customFields` is added to schemas for purchase order and purchase order line in `mod-orders` and `mod-orders-storage`.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> [MODORDERS-964] Add `customFields` to purchase order and purchase order line

mod-orders-storage/examples/routing_list_collection.sample, mod-orders-storage/examples/routing_list_get.sample, mod-orders-storage/schemas/routing_list.json, mod-orders-storage/schemas/routing_list_collection.json
[MODORDSTOR-364: Create routing_list table and API for it](https://folio-org.atlassian.net/browse/MODORDSTOR-364)
* Add a new migration to create table for routing lists
* Add to acq models: RoutingList, RoutingListCollection
* Add API for all CRUD operations
=> [MODORDSTOR-364] Create routing_list table and API for it

mod-orgs/examples/integration_detail_collection.sample, mod-orgs/examples/integration_detail_get.sample, mod-orgs/examples/integration_detail_post.sample, mod-orgs/schemas/edi_config.json, mod-orgs/schemas/edi_ftp.json, mod-orgs/schemas/edi_schedule.json, mod-orgs/schemas/integration_detail.json, mod-orgs/schemas/integration_detail_collection.json, mod-orgs/schemas/schedule_parameters.json
- <https://folio-org.atlassian.net/browse/MODORGSTOR-171>
- Add RAML-compatible models based on this Spring Boot-compatible model:
- <https://github.com/folio-org/folio-export-common/blob/master/schemas/acquisitions/vendorEdiOrdersExportConfig.json>
=> [MODORGSTOR-171]. Create Data Structure/Api to store Organization Integration details instead of mod-configuration

mod-orders-storage/examples/wrapper_piece_collection.sample, mod-orders-storage/examples/wrapper_piece_get.sample, mod-orders-storage/schemas/wrapper_piece.json
- <https://folio-org.atlassian.net/browse/MODORDERS-1237>
- Add additional `purchaseOrder`, `poLine` and `title` objects to `wrapper_piece.json` needed for effective filtering and sorting as required by the Claiming app
=> [MODORDERS-1237]. Add purchaseOrder and poLine objects

mod-finance/examples/fund_update_log.sample, mod-finance/schemas/fund_update_log.json
- <https://folio-org.atlassian.net/browse/MODFIN-416>
- Add `ledgerId` and `acqUnitIds` to the schema to improve filtering by AcqUnits, and make the schema open for potential ledger cascade deletion
=> [MODFIN-416]. Batch allocation logs - restrict by acq units

mod-orgs/schemas/address.json, mod-orgs/schemas/contact.json, mod-orgs/schemas/email.json, mod-orgs/schemas/phone_number.json, mod-orgs/schemas/url.json
[MODORG-34](https://folio-org.atlassian.net/browse/MODORG-34) - json schema for categories defines type string but folio actually requires UUID
Updated the schemas to enforce a UUID type.
[mod-organizations-storage PR](https://github.com/folio-org/mod-organizations-storage/pull/134) (will have to be updated when this PR is merged)
Ideally all of the PRs …
=> [MODORG-34] Change category type to UUID

mod-orders-storage/examples/po_line_collection.sample, mod-orders-storage/examples/po_line_get.sample, mod-orders-storage/schemas/eresource.json, mod-orders/examples/composite_po_line.sample
[MODORDSTOR-448](https://folio-org.atlassian.net/browse/MODORDSTOR-448) - Make user limit as string field & apply migration
Changed the type and updated examples.
- mod-orders-storage
- mod-orders
- mod-gobi
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …
=> [MODORDSTOR-448] Change type of eresource.userLimit to string

mod-mosaic/examples/mosaic_configuration.sample, mod-mosaic/schemas/mosaic_configuration.json
[[MODMO-6] Implement endpoint for storing Mosaic configuration options](https://folio-org.atlassian.net/browse/MODMO-6)
- Add a new model for mosaic configuration
=> [MODMO-6] Implement endpoint for storing Mosaic configuration options

mod-mosaic/examples/mosaic_order.sample, mod-mosaic/examples/mosaic_order_request.sample, mod-mosaic/schemas/mosaic_order.json
- <https://folio-org.atlassian.net/browse/MODMO-15>
- Add fields: `physical`, `eresource`, and `checkinItems`
- Remove fields: `userLimit`, `materialTypeId`, `materialSupplier` and `accessProvider`
- Update samples
=> [MODMO-15]. Implement additional mapping functionality for Mosaic orders

mod-finance/schemas/exchange_rate_source.json
- <https://folio-org.atlassian.net/browse/MODFISTO-526>
- Add missing metadata field to the schema so that it begins to be populated by the incoming requests
- Tested by recompiling mod-finance-storage and reinstalling the module locally with this command:
```bash
curl --location 'http://localhost:36014/_/tenant' \
--header 'x-okapi-tenant: diku' \
--header 'x-okapi-token:  ${TOKEN}' \
--header 'Content-Type: application/json' \
--data '{
"module_to": "mod-finance-storage:8.9.0-SNAPSHOT.409",
"parameters": []
}'
```
- The result in DBeaver:
> Metadata is now being added on any CRUD action
=> MODFISTO-526. Fix issue with missing metadata

mod-orders-storage/schemas/contributor.json, mod-orders-storage/schemas/piece.json, mod-orders-storage/schemas/product_identifier.json, mod-orders-storage/schemas/title.json
The FOLIO Query Machine would like to report on data from `mod-orders-storage` (currently, `pieces` and `titles`). To do this, Entity Types will be generated based on this schema information, and, to ensure data are displayed properly to users, we must add annotations to these schemas to control things like default field visibility. For more information on FQM and the entity type generation process, see [this article](https://github.com/folio-org/fqm-tools/blob/69aabb6cbc3f4a0a44383acbf011d070cac8c047/docs/generation/01-introduction.md).
If there are breaking changes, please **STOP** and consider …
=> [MODORDSTOR-486] Add FQM entity type schema annotations
